### ISSUE TITLE
ACL Manager does not recreate its REQ socket on error

### ISSUE THREAD

**Issue by plwhite** [Metaswitch/calico#111]
If the plugin restarts, then ACL Manager does not recreate the REQ socket. That means that ACL Manager is happily sending data into the void.

**Comment by plwhite** [comment]
It looks like : 

* There is no `networkheartbeat` code in the neutron plugin. So we cannot detect when the connection goes bad without changes to that side too. This is pretty much benign though since it is a `SUB` connection.
* The only time that the `REQ` socket ever even gets used is at start of day. It also should get used when the 

Net of this is that it's messy, and not clearly relevant in the very short term. It's certainly not a trivial fix to make.

**Comment by Lukasa** [comment]
Fixed in #114.
