### ISSUE TITLE
IPv6: Why does initial Router Solicit msg sometimes not reach Dnsmasq? (w/o a 10s delay)

### ISSUE THREAD

**Issue by neiljerram** [Metaswitch/calico#12]
In our IPv6 testing, we observe that - unless we insert a deliberate delay - sometimes a VM's initial Router Solicit message does not reach Dnsmasq.  For this reason we currently specify configuring

        net.ipv6.conf.eth0.router_solicitation_delay = 10

in the guest VM image.

But this shouldn't be necessary: we should understand in more detail what can cause that initial message not to get through, and fix that.

**Comment by fasaxc** [comment]
@neiljerram did this get resolved?

**Comment by neiljerram** [comment]
Sorry, no, not yet.

**Comment by fasaxc** [comment]
@neiljerram are you a good person to look at this?

**Comment by neiljerram** [comment]
I think 'no version' was probably the right state for this to be in - i.e. no particular reason for this to be seen as required for 1.0, or any earlier milestone.

**Comment by fasaxc** [comment]
@neiljerram sorry to pester but it's not obvious to me why this is not a high priority.  Asking people to change the config inside their VMs is a deal-breaker because that config is usually baked in by upstream.

What is the impact; does the VM just retry?

**Comment by neiljerram** [comment]
@fasaxc With your work to let router solicits through at all, have you been able to confirm or deny whether this is still a problem?

Anyway, I think we need to look at this again.  If the VM just retried, or if the situation was covered by the unsolicited periodic RAs, I'm not sure why I would have felt the need to recommend that router_solicitation_delay solution.  I think the impact was probably that something got wedged and IPv6 never worked thereafter - but I'm not sure, so we should retest.

Don't agree with you regarding VM changes. It seems to me that IPv6 adoption is not yet mature enough for VM images to have working IPv6 out of the box - at least for an OpenStack-like environment that wants to use DHCPv6 - so changes seem inevitable at the moment.

**Comment by fasaxc** [comment]
Since I fixed the iptables config to allow them, I've definitely seen RS packets go through as soon as the VM comes up.  I'm just going to close this unless we see it again.

**Comment by neiljerram** [comment]
What we should then do, though, is:

- modify our test IPv6 image so that it no longer has configuration for a 30s delay before sending its first Router Solicit

- verify that all our tests still pass

- remove our doc that tells people to put that configuration into their IPv6 image.
