### ISSUE TITLE
Reconsider all calls to time.time()

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico#120]
This note comes from [the documentation](https://docs.python.org/2/library/time.html#time.time):

> While this function normally returns non-decreasing values, it can return a lower value than a previous call if the system clock has been set back between the two calls.

This is problematic if we ever use `time.time()` to make scheduling decisions. I know Felix does (I wrote some of that code). In those situations we should really rewrite to use a monotonically increasing clock.

Unfortunately, a monotonic clock was only added to Python in 3.3. Sadly, that suggests that we may need to use either ctypes or cffi to get at the Linux monotonic clock. Useful resources include [this StackOverflow post](http://stackoverflow.com/questions/1205722/how-do-i-get-monotonic-time-durations-in-python).

**Comment by fasaxc** [comment]
We've used the monotime package in Gulfstream, it's a backport of the monotonic() call added in Python 3.

**Comment by fasaxc** [comment]
Added a work-in-progress monotonic-time branch.

**Comment by fasaxc** [comment]
Grepped the codebase and don't see any uses of time.time() that aren't simply for logging purposes.  We can live with for 1.0.

**Comment by plwhite** [comment]
Agreed. In fact, we could easily fix this by changing about three lines of code, so perhaps worth doing that and cleaning the issue, but no urgency and certainly not required for 1.0.

**Comment by Lukasa** [comment]
Ok, so I checked this out and @fasaxc is entirely right. Given that time.time() is used only for logging it doesn't matter too much what it actually returns, *especially* as it's logged at `debug` level. I think we can consider this *not* a bug.

However, this search did lead me to some code we don't actually use in Felix, so I may remove that.
