### ISSUE TITLE
Felix sends unnecessary heartbeats to ACL Manager.

### ISSUE THREAD

**Issue by plwhite** [Metaswitch/calico#122]
It repeatedly logs the following, showing that it is getting and erroring out all heartbeats on the GETACLSTATE connection.

    2015-01-20 01:24:48,832 [DEBUG] calico.acl_manager.acl_publisher 110: Sending response message: <binary stuff removed here> {"message": "Unknown message type: expected GETACLSTATE", "type": "HEARTBEAT", "rc": "FAILURE"}

**Comment by matthewdupre** [comment]
The ACL API doesn't specify (or need) heartbeats from Felix to ACL Manager.  ACL Manager doesn't need to track Felices, and the only unsolicited ACL Manager to Felix messages are over the PUB-SUB sockets which have an ACL Manager to Felix heartbeat.

On the query socket, all Felix needs to do is set a timeout on the wait for ACL Manager response after it sends a query, and treat failures there the same as it would a missed heartbeat.

**Comment by matthewdupre** [comment]
This is currently not blocking anything (since the ACL manager turns around unexpected responses anyway.

We need to review whether we should include these heartbeats and either rip them out or patch up the logging and update the API.

**Comment by plwhite** [comment]
For the record, I think the discussion above is wrong - these heartbeats are critical to ensure timely creation of endpoint configuration. We obviously need to discuss further.

**Comment by plwhite** [comment]
Superseded by PR #307.
