### ISSUE TITLE
Our Chef-based procedure for installing and starting Calico often fails with a failure to restart the calico-felix service

### ISSUE THREAD

**Issue by neiljerram** [Metaswitch/calico#137]
For example:

[2015-01-22T03:15:52+00:00] INFO: Processing apt_package[calico-compute] action install (calico::general_compute line 181)
[2015-01-22T03:16:05+00:00] INFO: apt_package[calico-compute] sending create action to template[/etc/calico/felix.cfg] (immediate)
[2015-01-22T03:16:05+00:00] INFO: Processing template[/etc/calico/felix.cfg] action create (calico::general_compute line 217)
[2015-01-22T03:16:05+00:00] INFO: template[/etc/calico/felix.cfg] backed up to /var/chef/backup/etc/calico/felix.cfg.chef-20150122031605.173214
[2015-01-22T03:16:05+00:00] INFO: template[/etc/calico/felix.cfg] updated file contents /etc/calico/felix.cfg
[2015-01-22T03:16:05+00:00] INFO: template[/etc/calico/felix.cfg] mode changed to 644
[2015-01-22T03:16:05+00:00] INFO: template[/etc/calico/felix.cfg] sending restart action to service[calico-felix] (immediate)
[2015-01-22T03:16:05+00:00] INFO: Processing service[calico-felix] action restart (calico::general_compute line 211)
[0m
================================================================================[0m
[31mError executing action `restart` on resource 'service[calico-felix]'[0m
================================================================================[0m

[0mMixlib::ShellOut::ShellCommandFailed[0m
------------------------------------[0m
Expected process to exit with [0], but received '1'
[0m---- Begin output of /sbin/start calico-felix ----
[0mSTDOUT: 
[0mSTDERR: start: Job is already running: calico-felix
[0m---- End output of /sbin/start calico-felix ----
[0mRan /sbin/start calico-felix returned 1[0m

[0mResource Declaration:[0m
---------------------[0m
# In /var/chef/cache/cookbooks/calico/recipes/general_compute.rb
[0m
[0m211: service "calico-felix" do
[0m212:     provider Chef::Provider::Service::Upstart
[0m213:     supports :restart => true
[0m214:     action [:nothing]
[0m215: end
[0m216: 
[0m
[0mCompiled Resource:[0m
------------------[0m
# Declared in /var/chef/cache/cookbooks/calico/recipes/general_compute.rb:211:in `from_file'
[0m
[0mservice("calico-felix") do
[0m  provider Chef::Provider::Service::Upstart
[0m  action [:nothing]
[0m  supports {:restart=>true}
[0m  retries 0
[0m  retry_delay 2
[0m  default_guard_interpreter :default
[0m  service_name "calico-felix"
[0m  pattern "calico-felix"
[0m  declared_type :service
[0m  cookbook_name "calico"
[0m  recipe_name "general_compute"
[0mend
[0m
[0m[2015-01-22T03:16:05+00:00] INFO: Running queued delayed notifications before re-raising exception
[2015-01-22T03:16:05+00:00] INFO: template[/etc/bird/bird.conf] sending restart action to service[bird] (delayed)
[2015-01-22T03:16:05+00:00] INFO: Processing service[bird] action restart (calico::general_compute line 205)
[2015-01-22T03:16:05+00:00] INFO: service[bird] restarted
[2015-01-22T03:16:05+00:00] ERROR: Running exception handlers
[2015-01-22T03:16:05+00:00] ERROR: Exception handlers complete
[2015-01-22T03:16:05+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-01-22T03:16:05+00:00] ERROR: service[calico-felix] (calico::general_compute line 211) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /sbin/start calico-felix ----
STDOUT: 
STDERR: start: Job is already running: calico-felix
---- End output of /sbin/start calico-felix ----

**Comment by neiljerram** [comment]
I think this is because the calico-felix package includes a non-working sample config, which is installed as /etc/calico/felix.cfg.  Felix starts up, reads this, and immediately exits because it can't resolve the "controller" name that the sample config has for PluginAddress.  The Upstart infrastructure then immediately restarts it again, and so on - in a cycle whose period is about 200ms.

At the same time, our Chef recipe is installing a correct /etc/calico/felix.cfg, then tells the calico-felix service to restart.  My guess is that the restart request (or whatever Chef now does) interacts badly with the 200ms cycle respawning, and we end up with the error as shown above.

So...  In fact there is no sensible 'default' config for Felix, and so the package installation process should not be creating one.  One could even imagine a scenario where 'controller' did resolve to something... but possibly not something that you'd really want Felix to connect to.  So Felix should actually require an explicit configuration step before it starts up.

Therefore I'm proposing the following changes.

- Rename our sample felix.cfg to felix.cfg.example, and install it as /etc/calico/felix.cfg.example.

- Change the upstart config so that it only starts Felix if /etc/calico/felix.cfg exists.

- Update our public install instructions so that they say that you need to rename felix.cfg.example to felix.cfg, after editing it.

- Change our Chef recipe so that it starts Felix - as opposed to restarting it - after installing a good felix.cfg.

**Comment by neiljerram** [comment]
All the same logic applies to ACL Manager too, so I propose similar changes for that.

**Comment by plwhite** [comment]
All sounds very sensible to me.

**Comment by Lukasa** [comment]
It's not clear here why we have to switch from 'restart' to 'start'. Upstart has no problem 'restarting' processes that were not previously started as far as I'm aware. That way the Chef configuration is a bit more resilient (Upstart *does* have a problem 'starting' things that are already running)

**Comment by neiljerram** [comment]
Are you sure?  I did some experiments by hand yesterday and they seemed to indicate the opposite: 'start calico-felix' complained if calico-felix was already running, and 'restart calico-felix' complained if calico-felix was not already running.

I don't think I checked $?, but there were definitely those complaints on stdout/stderr indicating that the operation had failed.

------------------

**Comment by Lukasa** [comment]
Really? From my Juju-based box:

```
ubuntu@calico-vm13:~$ sudo service calico-felix stop
calico-felix stop/waiting
ubuntu@calico-vm13:~$ sudo service calico-felix restart
stop: Unknown instance:
calico-felix start/running, process 24216
```

**Comment by neiljerram** [comment]
Can you try using '(re)start calico-felix' instead of 'service calico-felix (re)start'? I think the former is what Chef does.

------------------

**Comment by Lukasa** [comment]
Ah, there we go, that reproduces the problem. Ugh, that's annoying. Fair enough then, LGTM.
