### ISSUE TITLE
Felix iptables code does not log

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico#141]
This makes it hard to debug!

**Comment by plwhite** [comment]
We're restructuring this code - which means we absolutely will not fix this (though we do need to ensure that we log in the replacement). Hence tagging as `wontfix`.

**Comment by Lukasa** [comment]
We don't log in the restructured code, so I'm removing the `wontfix` label and re-assigning you @plwhite.

**Comment by fasaxc** [comment]
We do have logging in the iptables layer now.
