### ISSUE TITLE
ACL Manager depends on python-iptables on RHEL7.

### ISSUE THREAD

**Issue by matthewdupre** [Metaswitch/calico#148]

**Comment by matthewdupre** [comment]
This is caused by failing to set CALICODEPS=none during the build process.

**Comment by neiljerram** [comment]
FYI the Debian equivalent of this is the line

     export CALICODEPS = none

in debian/rules.  Hopefully there is some similarly straightforward Red Hat solution.

**Comment by matthewdupre** [comment]
I'm going to temporarily add the workaround (install python-iptables) into the instructions.  This needs to be removed when it's fixed.

**Comment by matthewdupre** [comment]
We've now removed python-iptables entirely, so this is no longer a problem.
