### ISSUE TITLE
Felix does a lot of shell commands that impact performance

### ISSUE THREAD

**Issue by plwhite** [Metaswitch/calico#150]
See https://github.com/Metaswitch/calico-docker/issues/3

We don't have enough measurements to show how bad this is in detail, but we know that with 4 endpoints, each resync triggers a few seconds of high CPU because of shelling out - which is enough to show that it is worrying and will impact real systems.

I decided to investigate by removing the "ipset" commands from Felix. The conclusion is that, on a single core and not incredibly fast VM with 4GB of RAM :

* Removing all the ipset shelling out turned the CPU use from 13% to 6% (total, over all processes, though Felix is the biggest share of that).
* Replacing all the ipset shelling out with shell calls to something else ("echo") to just measure the cost of a shell command left the CPU use at 13% (i.e. as bad as with ipset calls).
* Hence the cost of shelling out is about 7% of CPU (on this one box in this one case) - and since in the demo this is concentrated at short intervals, it's hardly surprising it's prohibitive.

**Comment by plwhite** [comment]
Diags (mpstat output) are here.

* [Normal production code](http://calico-jenkins/diags/150/standard.txt.gz)
* [All ipset shell commands removed](http://calico-jenkins/diags/150/cut.txt.gz)
* [All ipset shell commands replaced with "echo"](http://calico-jenkins/diags/150/echo.txt.gz)

**Comment by neiljerram** [comment]
I don't understand "Hence the cost of shelling out is about 7% of CPU".  Doesn't your test with "echo" indicate precisely the opposite, i.e. that

- the cost of "shelling out", as a general mechanism, is 0

- the cost of the "ipset" program, specifically, is 7%.

**Comment by nbartos** [comment]
Had a quick look at the code, and it appears that you're using Popen correctly (shell=False with all args as a python list instead of a space separated list).  So at least you shouldn't have the overhead (fork & exec * 2) of actually "shelling out", just the single fork & exec.

**Comment by plwhite** [comment]
Thanks. I'm a bit surprised that fork plus exec is quite so expensive, but it's something we'll have to look into more (my previous experience was that fork was cheap if the process was small, and Felix isn't all that large).

We have a plan just to reduce the number of shell commands we issue to tackle this, which I expect we'll be pressing on with in the near future, because we know this is an area where we just don't scale well enough.

**Comment by tomdee** [comment]
How about getting a bit closer to interacting with netfilter directly e.g. with http://nilvec.com/python-iptables.html

**Comment by nbartos** [comment]
Felix already uses python-iptables.

**Comment by Lukasa** [comment]
Indeed it does. In fact, we're looking at moving away from it because it's causing us distribution troubles with Red Hat and the OpenStack Interoperability Lab.

**Comment by nbartos** [comment]
It would be sad to use something less efficient like executing iptables manually just for distribution reasons :(  If you're creating deb's in a ppa or rpms in a yum repo already for calico, you could also just add that package in too.  And if you're only manually distributing packages, you could also just have one you built to download as well.

**Comment by plwhite** [comment]
Superseded by PR #307 (which reworks this code).
