### ISSUE TITLE
Calico mechanism driver does not correctly handle VM migration.

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico#152]
When a VM live migrate is issued in OpenStack, the mechanism driver is *supposed* to send the following messages:

- ENDPOINTDESTROYED to the Felix on the old host
- ENDPOINTCREATED to the Felix on the new host

Instead, it simply sends an ENDPOINTUPDATED to the Felix on the new host. The new Felix doesn't understand this and errors out, while the old Felix is never told what to do about the missing endpoint.

Logs for this can be found [here](https://gist.github.com/nbartos/474b7e3157776df69283) (search for ENDPOINTUPDATED to find the message flows).

**Comment by Lukasa** [comment]
Updates [on the list](http://lists.projectcalico.org/mail-archive/msg00190.html). The key thing is that I believe the mechanism driver is thoroughly confused about where this VM is. It seems to have send an ENDPOINTUPDATED for it to the new node, but keeps reporting it to the old one in RESYNCSTATE messages.

This situation lasts about 60 seconds.

That suggests to me that we're misreading the neutron database: I suspect that's where we should start our analysis. Log files are linked from the mailing list post linked above.

**Comment by neiljerram** [comment]
Candidate fixes for this are at https://github.com/Metaswitch/calico/tree/plugin-migration, but not yet tested at all.

**Comment by neiljerram** [comment]
Also see discussion further discussion on the mailing list under 'Live migration' subject.

**Comment by DaveLangridge** [comment]
I've repro'd this problem with migration. Then tested with this fix, which sends create not update. Works fine (with fix for #180).

**Comment by neiljerram** [comment]
Addressed by https://github.com/Metaswitch/calico/pull/191
