### ISSUE TITLE
L3 agent and OpenvSwitch appear enabled in Horizon UI for Calico

### ISSUE THREAD

**Issue by DaveLangridge** [Metaswitch/calico#162]
Install instructions stop these services, but they appear as 'Enabled' but 'Down' in the UI. confusing for the user. Some things showing as down indicate a problem, others don't.

**Comment by Lukasa** [comment]
This will happen if they've ever existed. I don't know that there's anything we can do about this, sadly.

**Comment by matthewdupre** [comment]
The rows for the neutron agents persist forever in the DB, but can be manually deleted if they aren't needed:

Log into the database, and then:
`use neutron;`
`SELECT * FROM agents WHERE agent_type LIKE '%Open vSwitch agent%'; # Review before deletion`
`DELETE FROM agents WHERE agent_type LIKE '%Open vSwitch agent%'; # Delete OvS agents`

Do you think this is worth adding to the installation process, or is it just additional clutter for insufficient benefit?

**Comment by fasaxc** [comment]
I think we should tell people to run "neutron agent-delete" and friends: #517
