### ISSUE TITLE
First ping from a VM can take over 1s

### ISSUE THREAD

**Issue by DaveLangridge** [Metaswitch/calico#164]
E.g. typical ping from a VM:
PING 192.168.0.8 (192.168.0.8) 56(84) bytes of data.
64 bytes from 192.168.0.8: icmp_seq=1 ttl=63 time=725 ms
64 bytes from 192.168.0.8: icmp_seq=2 ttl=63 time=0.094 ms
64 bytes from 192.168.0.8: icmp_seq=3 ttl=63 time=0.084 ms
64 bytes from 192.168.0.8: icmp_seq=4 ttl=63 time=0.145 ms
64 bytes from 192.168.0.8: icmp_seq=5 ttl=63 time=0.890 ms
64 bytes from 192.168.0.8: icmp_seq=6 ttl=63 time=0.087 ms

**Comment by fasaxc** [comment]
We've also seen this on in the docker prototype so it's not a VM issue.  I managed to capture a PCAP of the issue and it looks like it's the ARP that is taking the additional time.

**Comment by fasaxc** [comment]
Investigated further, looks like this is simply a tuneable sysctl: net.ipv4.neigh.<tapname>.proxy_delay.  The value is described here: http://man7.org/linux/man-pages/man7/arp.7.html

    proxy_delay (since Linux 2.2)
              When an ARP request for a known proxy-ARP address is received,
              delay up to proxy_delay jiffies before replying.  This is used
              to prevent network flooding in some cases.  Defaults to 0.8
              seconds.

I tried adjusting that value to 0 and my ARP response times dropped to <1ms.  I tried increasing it to 150 and the first ping packet time doubled to 1500ms.

I'll see if I can put up a pull req.
