### ISSUE TITLE
Plugin timeout for VM creation should be configurable.

### ISSUE THREAD

**Issue by DaveLangridge** [Metaswitch/calico#166]
We've tested with a delay of 0.75s each way, and that works fine. With a delay of 1s, creation of VMs on remote hosts fail. (Error: Failed to launch instance "new": Please try again later [Error: No valid host was found. ].)

This is going to be OK in most circumstances, but might need increasing for slow networks.

**Comment by plwhite** [comment]
Superseded by PR #307.
