### ISSUE TITLE
ACL Manager sends superfluous ACLUPDATE messages to Felix.

### ISSUE THREAD

**Issue by matthewdupre** [Metaswitch/calico#172]
Currently ACL Manager sends an unsolicited update for every endpoint whenever it receives any update for any endpoint (even no-op updates).  This puts unnecessary load on Felix, causing performance problems (see https://github.com/Metaswitch/calico/issues/167 for the Felix consequences).

It should instead calculate whether ACLUPDATEs are required properly:
- when an endpoint is queried, or
- when the calculated rules for an endpoint change.

**Comment by plwhite** [comment]
Fixed PR #173.
