### ISSUE TITLE
error.value unresolved according to PyCharm

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#175]
Loading up the felix code in PyCharm, I see a bunch of uses of <some exception>.value highlighted as unresolved by the semantic checker, are those supposed to be error.args[0] or am I missing something?

        except InvalidRequest as error:
            # Invalid request fields. Return an error.
            fields = {
                "rc": RC_INVALID,
                "message": error.value,
            }

**Comment by plwhite** [comment]
Fixed PR #201
