### ISSUE TITLE
Felix should block traffic from tap interfaces that are ENDPOINTDESTROYED

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico#185]
If we send an ENDPOINTDESTROYED message, it's possible that the tap device will remain around. However, we've removed its ACLs. This shouldn't be a security risk to the rest of the data center (the ACLs for the other machines should cover them) but it does allow the VM to send traffic out of the data center when it really shouldn't be able to.

This should be forbidden. There are a number of ways we *could* do this (turn off forwarding on a per-interface basis on ENDPOINTDESTROYED, add iptables rules to drop them, etc.), but I don't have a strong opinion as to what to do at this stage.

**Comment by fasaxc** [comment]
I think we do this in etcd felix.
