### ISSUE TITLE
How should the Calico plugin / mech driver depend on Felix liveness?

### ISSUE THREAD

**Issue by neiljerram** [Metaswitch/calico#19]
The current Endpoint API - in particular the RESYNCSTATE semantics - strongly suggests that there can be an accumulated set of {endpoints for a given host to handle} _before_ the Felix on that host is actually running.  Otherwise, why would the 'endpoint_count' field be needed on the RESYNCSTATE response?

Now that's not a watertight argument (and hence I only say 'strongly suggests'), because the RESYNCSTATE semantics are also useful in a scenario where a Felix instance transiently stops and then restarts, e.g. for a software fix.  However, so far I've been implicitly assuming that the semantics are broader than that, i.e. as 'suggested' above.

In the case of the OpenStack plugin, this specifically means that the ML2 mechanism driver says 'Yes, I can provide connectivity for such-and-such port on such-and-such host', even if it doesn't have a current connection to a Felix instance on that host, and doesn't know if and when such a connection might materialize.

So, is that correct?

As a comment, the normal OpenStack semantics probably are a bit useful, and so we should be careful about losing them.  What they achieve is that if you have N compute hosts, but a required agent is not running (for any reason) on 1 of those, then VMs will only be created on the N-1 hosts that have the required agent running.

**Comment by plwhite** [comment]
Closing this issue. We have :

* Fixed up the related issue #79.
* Added some test cases to the test plan.
