### ISSUE TITLE
Drop privileges

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico#190]
Right now Felix has to run as root. This is generally a bad idea: the more processes that run as root on a box, the higher the risk surface on that box.

In an ideal world, Felix should have only the privileges it needs to do its job. We can achieve this by using [Linux capabilities](http://man7.org/linux/man-pages/man7/capabilities.7.html). A quick read of the man page suggests Felix definitely needs CAP_NET_ADMIN. It may need another capability for its use of procfs, but I'm not sure yet.

The simplest way to do this would be for the init scripts to daemonize Felix as another user running with CAP_NET_ADMIN. Not sure how to do this exactly. Alternatively, we can have Felix do this itself: be launched as root and give itself CAP_NET_ADMIN, then drop to a different UID.

**Comment by Lukasa** [comment]
Note that the ACL manager doesn't have to run as root at all.

Ideally BIRD wouldn't run as root, but it's not our code so I won't try to change it.

**Comment by alexwlchan** [comment]
There's a [section in the BIRD docs](http://bird.network.cz/?get_doc&f=bird-1.html#ss1.4) which also talks about privileges. I've only skimmed it, but might be worth looking in to further if/when we get around to implementing this.

**Comment by Lukasa** [comment]
So I think we can do this with systemd pretty easily by adding the following stanza to the `service` section:

```
CapabilityBoundingSet=CAP_NET_ADMIN
```

That would allow us to drop Felix down to its own user and then run with only the required privileges. This is a win in RPM systems. In upstart systems that'll be a bit harder, but I think we can still do it, we just need to fiddle about a bit more.

**Comment by Lukasa** [comment]
Ah, we also need CAP_NET_RAW I think, because we create a raw socket for listening to netlink. So:

```
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_RAW
```

**Comment by Lukasa** [comment]
Alright, this isn't as simple as it looks, so I think we won't do it.

Firstly, we can't do it on systems using upstart. This is because upstart doesn't understand capabilities, so we have to `setcap` the `calico-felix` executable before execution. The eagle-eyed will notice that this doesn't actually work because `calico-felix` isn't the relevant executable, *python* is. We obviously don't want to give CAP_NET_ADMIN and CAP_NET_RAW to all Python scripts on the box, so that's a non-starter.

Secondly, even if that wasn't a problem, we *also* have to do a `setcap` on `xtables-multi` and `ipset`. This `setcap` won't actually give all users on the box privileges to use them, but it's nonetheless something that will likely make sysadmins quite nervous.

Altogether Linux just doesn't seem to be well-suited for this. It'd be better to look at containerizing Felix on all systems (not just calico-docker systems) rather than pursuing this further.
