### ISSUE TITLE
No Felix response for ENDPOINTDESTROYED for absent endpoint

### ISSUE THREAD

**Issue by neiljerram** [Metaswitch/calico#192]
If Felix gets an ENDPOINTDESTROYED request for an endpoint that it doesn't recognize, it doesn't send any response back.

The code in handle_endpointdestroyed just logs and returns, in that case.  It should be more similar to what handle_endpointupdated does in the absent endpoint case.

**Comment by Lukasa** [comment]
I feel like I mentioned this in a previous moment, but maybe I didn't. Certainly can't find any evidence of it.
