### ISSUE TITLE
Felix failed to apply rules for new VM (covering all ports)

### ISSUE THREAD

**Issue by DaveLangridge** [Metaswitch/calico#197]
The security group I was using had an ingress rule 'all udp' for ports 1-65535.

This appeared to add a rule for each port:
...
0.0.0.0/1,udp:44070
0.0.0.0/1,udp:5588
0.0.0.0/1,udp:42250
0.0.0.0/1,udp:56377
0.0.0.0/1,udp:57262
0.0.0.0/1,udp:11978
etc

Adding a new VM I got:

2015-02-16 09:37:57,465 [ERROR] calico.felix.frules 691: Failed to add IPv4 inbound rule (0.0.0.0/1,udp:1-65535) for 6c10f3ce-59
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/calico/felix/frules.py", line 686, in update_ipsets
    ipsets.add(ipset, cidr + ipset_value)
  File "/usr/lib/python2.7/site-packages/calico/felix/ipsets.py", line 62, in add
    futils.check_call(["ipset", "add", name, value, "-exist"])
  File "/usr/lib/python2.7/site-packages/calico/felix/futils.py", line 89, in check_call
    raise FailedSystemCall("Failed system call", args, retcode, stdout, stderr)
FailedSystemCall: Failed system call (retcode : 1, args : ('ipset', 'add', 'felix-tmp-port', u'0.0.0.0/1,udp:1-65535', '-exist'))
  stdout  :
  stderr  : ipset v6.19: Hash is full, cannot add more elements

**Comment by plwhite** [comment]
Can you grab the Felix logs?

I suspect ACL Manager is giving us something we don't like, most likely converting the udp rule into a "block udp from ports 1 to 65535" and we then turn that into 65,535 rules. Which isn't very clever at all.

**Comment by matthewdupre** [comment]
FYI ACL Manager doesn't do any translation on port ranges, and rules are always allow (relative to the default of deny).

This rule would go through as allow UDP on ports 1 - 65536.

**Comment by DaveLangridge** [comment]
Diags for cotrol/compute node https://transfer.sh/KTn7X/2015-02-16-14-25-57.gz
Diags for compute node https://transfer.sh/py7oJ/2015-02-16-14-22-28.gz

Error at 14:21:40 is deleting a VM.

**Comment by plwhite** [comment]
This issue is no longer applicable, since we have new Felix code to which it does not apply.
