### ISSUE TITLE
Saying 'all UDP traffic' leads to terrible ipsets.

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico#205]
If you add a security group rule that says 'any UDP port' or 'any TCP port' in OpenStack, that translates into a port range of 1-65535. That causes Felix to create an ipset with 65535 entries. In addition to being a gratuitous waste of memory (1.5 MB for those entries alone) it causes Felix to stop inserting new rules, as per issue #206.

**Comment by plwhite** [comment]
Duplicate of issue #197
