### ISSUE TITLE
Felix has an undocumented upper bound on the number of rules in a security group.

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico#206]
When Felix creates an ipset it has a maximum size of 65536 rules. If that size is exceeded further elements do not get added to the ipset. This leads to transparent failure to correctly program security group configuration. This is exacerbated by #205.

**Comment by fasaxc** [comment]
Reading the AWS docs the other day, I think they limit security groups to 50 or 100 rules.  (Of course, that's not much help if one rule is expanded to 65000 ipset entries ;) )

**Comment by Lukasa** [comment]
Agreed. I don't really care what we do here, but if we have an upper bound it certainly shouldn't be *undocumented*. =)

**Comment by plwhite** [comment]
I think this issue goes away with PR #307, so closing it down. If we find that there are still problems of this nature, we'll open another issue.
