### ISSUE TITLE
Felix incorrectly assumes that ipsets treat port 0 as 'all ports'.

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico#207]
Per the comment on line 623 of `frules.py`, Felix believes that port 0 means 'all ports' in ipsets. Based on my testing this is untrue, and I can find no support for this view in the man page.

**Comment by plwhite** [comment]
Turns out that you can create such rules quite successfully, but they don't work, at least not on the version I was running with. The correct way to specify them is to give them as port range 1 to 65535, which then hits issue #197.

**Comment by Lukasa** [comment]
Resolved in #223.
