### ISSUE TITLE
Improvements to the Neutron driver code handling Felix connections

### ISSUE THREAD

**Issue by neiljerram** [Metaswitch/calico#213]
- The plugin should try to re-establish its outbound connection to Felix on receipt of a HEARTBEAT from Felix, as well as on receipt of a RESYNCSTATE request - because receiving a HEARTBEAT indicates that Felix is there.  However this will require a little careful state, because the HEARTBEAT message does not include the Felix hostname to connect out to.  The state needed is mapping {from 0MQ-connection-ID to hostname}, for each Felix-initiated connection that has delivered a RESYNCSTATE request.

- As noted in other issues, we need to stop logging binary characters for 0MQ connection ID (aka 'peer').

- Each distinct green thread in mech_calico.py should log with a consistent prefix that identifies the thread.  Currently they don't, and it's difficult to tell what is what.

- The thread for sending HEARTBEATs to Felix is currently per-hostname, and I wonder if it should be per-connection instead?

**Comment by fasaxc** [comment]
Pre-etcd: closing.
