### ISSUE TITLE
Use iptables-restore to inject rules faster

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#227]
Came across this while reading the iptables FAQ.  Unless this information is out-of-date, turns out that the normal iptables command copies the whole table to userspace, updates it there and then copies it back to kernel space again for every call, making running a sequence of iptables commands O(n^2).  (Presumably also the reason that iptables struggles with concurrent invocations.)

http://www.iptables.info/en/iptables-save-restore-rules.html

The article suggests using iptables-restore to inject multiple rules in one round-trip.  Essentially, you can write iptables commands to its stdin and then write a "COMMIT" instruction to tell it to copy the table into place. The commit is rumoured to be atomic and shouldn't even drop packets.  Sadly, they do flag up that the tool doesn't support every match type.

**Comment by plwhite** [comment]
This is clearly superseded by PR #307, so closing down issue.
