### ISSUE TITLE
frules.py using /64 for an IPv6 address

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#234]
Our anti-spoofing rules (frules.py:377) use a /32 for an IPv4 address but a /64 for IPv6 (even though an IPv6 address is 128 bits long).  Is that correct, are we really expecting each endpoint to have a /64?

@liljenstolpe was a bit worried when I told him that but maybe we're missing something.  At least feels like it should be configurable.

**Comment by plwhite** [comment]
That's a bug. It should be a 128.

**Comment by plwhite** [comment]
Superseded by PR #307
