### ISSUE TITLE
Log files are all confused

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico#249]
Our default logging configuration for Felix (at least on Ubuntu) causes logs to end up all over the place.

Felix chooses to log to `/var/log/calico`, and wants to rotate its own log files. However, at least one other process wants to do that too, which means that `/var/log/calico` looks like this:

```
ubuntu@calico04:~$ ls -lah /var/log/calico
total 16M
drwxr-xr-x  2 root root   4.0K Mar  9 06:47 .
drwxrwxr-x 14 root syslog 4.0K Mar  9 06:47 ..
-rw-r--r--  1 root root      0 Mar  9 06:47 felix.log
-rw-r--r--  1 root root    14M Mar  9 08:45 felix.log.1
-rw-r--r--  1 root root      0 Feb 27 06:55 felix.log.2015-02-26
-rw-r--r--  1 root root      0 Feb 28 06:28 felix.log.2015-02-27
-rw-r--r--  1 root root      0 Mar  1 06:53 felix.log.2015-02-28
-rw-r--r--  1 root root      0 Mar  2 06:36 felix.log.2015-03-01
-rw-r--r--  1 root root      0 Mar  3 06:26 felix.log.2015-03-02
-rw-r--r--  1 root root      0 Mar  4 06:27 felix.log.2015-03-03
-rw-r--r--  1 root root      0 Mar  5 06:34 felix.log.2015-03-04
-rw-r--r--  1 root root      0 Mar  6 06:30 felix.log.2015-03-05
-rw-r--r--  1 root root      0 Mar  7 06:43 felix.log.2015-03-06
-rw-r--r--  1 root root      0 Mar  8 06:39 felix.log.2015-03-07
-rw-r--r--  1 root root   892K Mar  8 11:40 felix.log.2.gz
-rw-r--r--  1 root root   895K Mar  7 11:40 felix.log.3.gz
-rw-r--r--  1 root root   898K Mar  6 11:40 felix.log.4.gz
```

Note the large numbers of empty files being rotated by some other process, while felix logs to `felix.log.1` and correctly rotates those logs out.

Additionally, Felix logs to stdout by default, which means another set of logs are available in `/var/log/upstart`:

```
ubuntu@calico04:~$ ls -lah /var/log/upstart
-rw-r-----  1 root root   1.3M Mar  9 08:49 calico-felix.log
-rw-r-----  1 root root   890K Mar  9 06:47 calico-felix.log.1.gz
-rw-r-----  1 root root   888K Mar  8 06:39 calico-felix.log.2.gz
-rw-r-----  1 root root   902K Mar  7 06:43 calico-felix.log.3.gz
-rw-r-----  1 root root   894K Mar  6 06:30 calico-felix.log.4.gz
-rw-r-----  1 root root   905K Mar  5 06:34 calico-felix.log.5.gz
-rw-r-----  1 root root   899K Mar  4 06:26 calico-felix.log.6.gz
-rw-r-----  1 root root   899K Mar  3 06:26 calico-felix.log.7.gz
```

This is really excessive, and doesn't gain us anything: we're just doing work we don't need to do.

My personal preference would be to disable Felix's logging to file, allowing the init process to control how Felix logs, but I'm open to other suggestions.

**Comment by Lukasa** [comment]
I suspect the duplicate log rotation in /var/log/calico comes from the fact that [this file](https://github.com/Metaswitch/calico/blob/master/debian/calico-felix.logrotate) is present.

**Comment by ed-harrison** [comment]
This feels like an area we should address before v1.0 as it is going to make our diagnosis of problems trickier.  Assigning to @matthewdupre as he is likely to have some resource available to look at issues over the next few weeks.

**Comment by matthewdupre** [comment]
This is likely similar to #624.

**Comment by plwhite** [comment]
I think it is in fact exactly the same issue - so we should close as a duplicate, though I could be persuaded I'm wrong.
