### ISSUE TITLE
ACL Manager seems to get confused and joins to multiple mechanism drivers simultaneously

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico#255]
Following on from [this thread](http://lists.projectcalico.org/mail-archive/msg00226.html) on the mailing list, we have a scenario where ACL manager appears to get lost and become unable to configure any endpoints until it restarts.

**Comment by matthewdupre** [comment]
Just pulled out what I think are the salient points from the log.  See the email thread for higher level discussion.

I followed VM eb8084bb5 (10.16.3.9) through.  It performs a number of migrations properly, but Felix doesn't get the security configuration after one from host 10.16.0.11 to 10.16.0.12 at 17:56:44.

17:54:49: VM migrates to host 10.16.0.11 successfully, receiving the security rules from ACL Manager (10.16.0.12)
17:55:09 ACL Manager starts up on 10.16.0.13 - it sends a GETGROUPS (that should trigger start of day synchronization) to the mechanism driver on 10.16.0.13.
17:55:11 10.16.0.13 mechanism driver returns the GETGROUPS, but then the neutron DB query crashes out and the neutron-server instance is never heard from again.
17:55:49: Mechanism driver on 10.16.0.11 sends a heartbeat to ACL Manager on 10.16.0.13.
17:56:19: Another heartbeat (and so on).
17:56:44: VM migrates to host 10.16.0.12, but ACL Manager (10.16.0.13, not .12) doesn't know about the endpoint.
18:01:53 ACL Manager starts up (on 10.16.0.12), and pushes out the right security, which Felix programs.

**Comment by nbartos** [comment]
Note that there is only one instance of neutron-server at any one time, it just migrates (with the same floating IP) from server to server when necessary.  The same is done with the Calico acl-manager.

**Comment by matthewdupre** [comment]
I've had a look at the latest set of diags (http://lists.projectcalico.org/mail-archive/msg00247.html), given #257, but I can't (yet) identify a symptom.  @nbartos - could give me a bit more info about the test that's failing (for example, pinging from where to where, and when) please?

**Comment by nbartos** [comment]
The tests are all varying degrees of live migrating VMs around, killing and restarting services, and rebooting servers.  The pings I did were all from outside the cluster.  I'm attempting to reproduce it in such a way were another subsequent test won't clobber the state so I can collect more data.

**Comment by nbartos** [comment]
So far all of my repros indicate the actual problem is that qemu is causing a guest kernel panic after migration.  I was aware of this happening occasionally before, however for some reason using Calico causes this to happen much more often.  I'm guessing it's either faster or slower at some point, exacerbating a live migration race condition.

Since that seems to be unrelated, I believe this is good for merge.

**Comment by Lukasa** [comment]
Resolved in #257.
