### ISSUE TITLE
Gateway MAC addresses always need to be the same

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico#261]
To ensure that endpoint migration works seamlessly, we require that all endpoints see the same MAC address for their gateway. If they don't, they run the risk of carrying a poisoned ARP cache around with them.

In OpenStack we currently have a patch in our Nova fork to achieve this. We don't want to maintain the patch forever, so we'd ideally like to use a supported hook to achieve the same effect. Some others (mleroy, beagles) are working on a proposal for scripts on pluggable VIF types, which we hope will allow us to achieve the function we need. For the moment this work is being tracked on [this etherpad](https://etherpad.openstack.org/p/nova_vif_plug_script_spec): I'll keep this issue up to date to track its progress.

**Comment by ed-harrison** [comment]
We've now proposed an upstream nova change to provide this function (not part of the pluggable VIF stuff, based on @neiljerram's analysis of the options) and have that change in our own fork.  Not sure why we need to track this as a separate issue (i.e. I don't think we have issues to track the other proposed upstream changes).

**Comment by Lukasa** [comment]
Agreed, we don't need to track this separately.
