### ISSUE TITLE
RHEL 6.5 instructions not correct for bird

### ISSUE THREAD

**Issue by DaveLangridge** [Metaswitch/calico#267]
service bird restart
bird: unrecognized service

It works from command line, 'bird -c /etc/bird/bird.conf'. But this will not restart over reboot.

**Comment by Lukasa** [comment]
Yup, so the problem here is that on RHEL 6.5 we install BIRD from source but don't put an upstart service file in place.

That's just a straight oversight.

**Comment by ed-harrison** [comment]
Fixed in the documentation as part of  #284.
