### ISSUE TITLE
ACLManager doesn't send update when endpoint removed from group

### ISSUE THREAD

**Issue by spikecurtis** [Metaswitch/calico#269]
Noticed on v0.13, but presumably on much earlier versions.

If an endpoint is in a single group, then is removed from the group via the Network API, ACLManager fails to send an ACLUPDATE. This mean the corresponding Felix preserves the ACLs from the group for that endpoint.

To see this in action, create a group with two members and rules inbound: from group, outbound: allow all.  Ping from one endpoint to the other.  This works.  Remove one endpoint from the group (such that is it in no groups).  Pings still work.

The cause is in the way ACL manager computes ACLUPDATEs --- it computes a list of endpoints by spinning through all the groups, then computes ACLs for each.  Since the endpoint in question is not in any groups, it never gets its ACLs recomputed.

**Comment by neiljerram** [comment]
I think there’s also a plugin bug in this area: see https://github.com/Metaswitch/calico/issues/163.

**Comment by spikecurtis** [comment]
@neiljerram Interesting!

I don't think you were implying this, but to avoid doubt: #163 cannot be the cause of this issue.  I saw this behavior on calico-docker and confirmed that the GROUPUPDATE over the Network API is being sent.

**Comment by plwhite** [comment]
I think in the light of PR #307, we should close this issue.
