### ISSUE TITLE
Resyncstate error after migration

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico#299]
From [the mailing list](http://lists.projectcalico.org/mail-archive/msg00251.html):

Nick Bartos:

> When running the usual barrage of tests that perform VM and service
migrations, I was able to get into a state where a VM (10.43.3.3) was
inaccessible.  I waited some time (~30 mins) and tried to get to the same
VM, and it worked.  Doing a quick diff of the diags before and after, I see
that the route for 10.43.3.3 didn't exist on any node when it was broken.
>
> Here is the output of diag.sh when the problem was happening:
https://gist.github.com/nbartos/5d5651bef6f0bed2ddd4/raw/3dd2498c39fceeb577dd4047712abf19f3d09381/before-node16.tar.xz
https://gist.github.com/nbartos/5d5651bef6f0bed2ddd4/raw/c5500da319bbba070e1732003c60a6bcd1b9672d/before-node17.tar.xz
https://gist.github.com/nbartos/5d5651bef6f0bed2ddd4/raw/before-node18.tar.xz
> 
> Here's the output of diag.sh after the problem fixed itself:
https://gist.github.com/nbartos/5d5651bef6f0bed2ddd4/raw/09cf305d0c13bb76511f9c51c4bc9de356d1f0c7/after-node16.tar.xz
https://gist.github.com/nbartos/5d5651bef6f0bed2ddd4/raw/cb0b9dc2f387a1deee6dcfd087ecdc49270fc676/after-node17.tar.xz
https://gist.github.com/nbartos/5d5651bef6f0bed2ddd4/raw/723ce45bb4a7f25010991967ea3265f5a9617509/after-node18.tar.xz
> 
> Here's the single syslog from all nodes combined:
https://gist.github.com/nbartos/5d5651bef6f0bed2ddd4/raw/syslog.tar.xz

Me: 

> So, here's an initial timeline of events.
> 
> 1. At 20.35.50.482655, host 17 receives an endpoint creation event for VM 10.43.3.3, part of a migration of that endpoint.
> 2. At 20:35:50.749728, basic programming of that endpoint finishes.
> 3. By 20:35:50.949633, ACLs are in place too.
> 4. At 20:36:45.232517, one minute later, Felix on host 17 begins state resynchronization. At this point, Felix is told that it owns no endpoints, so it immediately tears down the programming for the endpoint.
> 
> Nothing is heard about this endpoint again on that host.
> 
> This is thoroughly puzzling, because all messages were processed by the same neutron server process, and we only send the endpoint creation event after the database commit has finished. That makes it hard to understand how the same process could, one minute later, scan the database and *not* find that endpoint. 
> 
> However, it's worth noting that just after the migration finishes basically everything explodes. Rabbit dies, MySQL dies, and then zookeeper appears to fall over as well, leading savage to rebuild basically everything. If it's even remotely possible that MySQL did not properly store that transaction it would give a compelling explanation for how this bug occurred.

Nick:

> MySQL is ran on a synchronously mounted and synchronously replicated
network filesystem, and was configured to make sure writes in MySQL itself
are done synchronously as well.  This does result in a slow MySQL instance,
but the resulting consistency is necessary in an environment where a node
can die and the MySQL instance must be moved to another node.
> 
> So far, I haven't seen any transactions lost during any tests since we
implemented this a long time ago.  I'm not saying it's impossible that a
transaction was lost, but we did spend quite a bit of effort trying to make
sure that never happened.
> 
> An interesting thing is that the problem did correct itself without me
doing anything other than letting it sit for a while.  After I left it, no
services should have been killed/migrated.  If a SQL transaction really was
lost/deleted, I don't see how it would explain the self-healing aspect of
what I observed.

**Comment by Lukasa** [comment]
So Nick's final point is a strong one: if the transaction got lost the only way it could self-heal is if the transaction was delayed. I'd believe that could happen if Nick was using, say, Galera Cluster, but his description makes it clear that he isn't, so that argument goes out of the window.

The question then becomes: how can we possibly see stale data in this instance?

**Comment by Lukasa** [comment]
Some relevant notes: the migration that is occurring is finished from the perspective of the Neutron DB: the `update_port_postcommit` has been called at `20:35:50.466220`, well in advance of the RESYNCSTATE. We even finish that method well in advance of the RESYNCSTATE, so that database transaction should be comitted and clean.

**Comment by Lukasa** [comment]
Hmm, our handling of the database doesn't seem to be obviously wrong from a code read, so for now I'm putting that aside.

**Comment by Lukasa** [comment]
The VM was migrated from .18 to .17. .17 resynchronized at 20:36:45.252563 and was told it had no VMs. .18 resynchronized at 20:40:27.427927 and was also told it had no VMs. At least one of those messages had to be in error.

**Comment by Lukasa** [comment]
It is extremely difficult to understand this problem if the database was functioning cleanly and correctly.

**Comment by Lukasa** [comment]
@nbartos If you're able to reproduce this with any degree of consistency, can you please try to run 'neutron port-list`? I'd like to see where neutron thinks this port is.

**Comment by Lukasa** [comment]
@nbartos If you're able to reproduce this with any degree of consistency, can you please try to run 'neutron port-list`? I'd like to see where neutron thinks this port is.

**Comment by nbartos** [comment]
It hasn't been consistent, and unfortunately it's often hard to gather more data after the fact, since mostly it runs through the CI which unfortunately clobbers the state after another test is launched after it.

**Comment by Lukasa** [comment]
That makes a lot of sense.

It might help if I try to explain my line of thinking, in case you find yourself in a situation where you can take a quick look.

The logs clearly show the same neutron server process is communicating at all times. This gives us some important ordering requirements in Neutron: we know that the ordering of logs in-process matches the genuine ordering of events.

That means when we got called in the post-commit hook to commit the migration, Neutron *must* have committed the port update transaction. It is extremely hard to believe that, at any level of transaction isolation, we could possibly issue a read that is out of date with respect to that commit *especially* when that read is logged in-process (so we know when it happened with respect to the post-commit hook).

I really don't see how this database row can have been manipulated under our feet, or otherwise have not been committed, unless a problem was encountered with the database itself.

**Comment by nbartos** [comment]
I agree, it's baffling.

**Comment by Lukasa** [comment]
So the things I want to know (and @nbartos, you almost certainly don't have all this information to hand):

- does anything happen to the database to trigger this? (e.g. crashes)
- is neutron-server secretly getting moved under our feet without the logs making that apparent? (hard to believe, the PID is being logged out, but stranger things have happened)
- more generally, is there any consistent theme or trigger when this happens?

**Comment by Lukasa** [comment]
This mystery bug should go away when we move to etcd, so fixing it is no longer a priority in this dev cycle. =)
