### ISSUE TITLE
Neutron drops subnet prefix length

### ISSUE THREAD

**Issue by alexaltair** [Metaswitch/calico#306]
This is a bug for the calico patch of neutron.

When you create an IPv6 subnet in OpenStack you specify the prefix and the length. Neutron fails to pass the length into `dnsmasq`. `dnsmasq` assumes a default length of 64, and so the prefix gets cast to that length.

Diagnosed by seeing the following in `/var/log/syslog`;

```
Mar 31 01:01:38 calicobobcat-ci02 dnsmasq-dhcp[2009]: DHCPv6, static leases only on fd5f:5d21:845:1c2e:2::, lease time 1d
Mar 31 01:01:38 calicobobcat-ci02 dnsmasq-dhcp[2009]: router advertisement on fd5f:5d21:845:1c2e::
```

**Comment by fasaxc** [comment]
@Lukasa, not sure who owns the neutron plugin, please can you triage?

**Comment by neiljerram** [comment]
It's me.

**Comment by fasaxc** [comment]
@neiljerram did this get resolved?

**Comment by neiljerram** [comment]
Yes.
