### ISSUE TITLE
How do we initialise etcd?

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico#311]
There are several bits of etcd data structure that various components (mostly Felix) simply assume is there, and they either crash or fail if it's not present. We need a position about how that data gets into etcd.

**Comment by neiljerram** [comment]
It's really just /calico/config that we don't understand, isn't it?  For host and profile data, it's clearly the plugin's job to populate that.  For the Felix status TTL key (when we specify it), it will clearly be each Felix's job.

**Comment by apollitt** [comment]
The plug-in is responsible for populating etcd (starting from a completely blank etcd).  Once etcd is in a consistent state then the plug-in will set a well known top level calico key to say it is ready.  Until that point Felix will not process the etcd data (and must be robust to nothing being there at all).  The Felix status TTL key is the possible exception in that Felix may the the component that creates that, but I'm not sure if we have done the data model design for that (beyond us saying we can use TTL so it should be really easy).

**Comment by apollitt** [comment]
Note that the Felix code for handling etcd not being in a ready state is not written yet!

**Comment by Lukasa** [comment]
@apollitt agree for the most part, with one note:

Who is responsible for creating the `/calico/host/<host>/` subkeys (`/config` and `/endpoint`)? It feels like the plugin shouldn't do that necessarily, unless we have some way of triggering a plugin that a new Felix instance exists.

**Comment by neiljerram** [comment]
https://github.com/Metaswitch/calico/pull/313 enhances the plugin to provide the /calico/config/InterfacePrefix value that Felices need in an OpenStack system.  For all the other config values, the default values are good, so I don't believe we need to explicitly provide them.

**Comment by fasaxc** [comment]
Felix now waits for the config to be present, and #407 covers the remaining missing pieces, I think.
