### ISSUE TITLE
Minor: plugin shouldn't write null for unused fields in rules

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#317]
It's allowed by felix but the intention was to only supply the things that we want to match on.  If nothing else it keeps the data small.

{"ip_version": 4, "dst_net": "0.0.0.0/0", "dst_tag": null, "dst_ports": null}

**Comment by neiljerram** [comment]
‎Thanks, I'll fix this on Tuesday if not sooner.

**Comment by fasaxc** [comment]
Since it was trivial, and I was making a fix on the relevant line of code, I fixed this on my branch.

**Comment by fasaxc** [comment]
Fixed in b48e350d373d6e0ad08d50de57723681921354a0.
