### ISSUE TITLE
Avoid thundering herd issues around reconnecting to etcd/start-of-day

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#324]
As we scale up to 100s of nodes, we may need felix to be smarter about connecting to etcd at start-of-day.  this probably involves introducing exponential backoff or some other throttling mechanism.

Right now, it'll just connect ASAP.

**Comment by fasaxc** [comment]
Steer from @apollitt is to defer this until we find out what scale we start to hit issues.  Then we'll be in a position to do something appropriate.

**Comment by matthewdupre** [comment]
This should also cover jittering any resyncs.

**Comment by neiljerram** [comment]
Per @lxpollitt steer above, do we yet know the scale where we hit issues?  If not, I'll punt this out to the 1.0 milestone.

**Comment by fasaxc** [comment]
@matthewdupre I thin the next action is to find out what the limits are, which probably comes under your scale testing umbrella.

**Comment by plwhite** [comment]
I'm keen not to fix this until we know that there is an actual problem - to the point where my preference is to just close the issue and do nothing. If etcd can happily feed and water the herd, let them thunder away. If it can't, we can spread them out a bit.

**Comment by matthewdupre** [comment]
@plwhite Agreed - since you own the scale test plan, can you please try and find out whether this is an actual problem.

**Comment by plwhite** [comment]
Agreed. Doing nothing until we know there is a real problem here.

**Comment by Lukasa** [comment]
Given that we're doing nothing for now I'm going to close this issue. I'm trying to schedule work for these things, and if we're not even possessed of a belief there's a problem there's no point having this hanging around.
