### ISSUE TITLE
Plugin should set Ready flag at correct time

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#328]
Felix now supports a flag to tell it that the etcd data model is in sync.  Right now that flag is always set by the plugin, which mimics the old felix behaviour (actually, it's slightly nicer because we set the flag after setting the other system-wide etcd config).  

However, the plugin _should_ set the flag only when etcd really is in sync.

Note: felix does support setting the flag back to false but that should be a very rare operation.  It effectively disables all felices and causes them to resync when the flag is set again.

**Comment by fasaxc** [comment]
@neiljerram I think this belongs with you as the plugin owner.

**Comment by neiljerram** [comment]
Agreed, thanks.

I think there is some subtlety here and multiple possible solutions.

- Currently I think the plugin behaviour is technically wrong, because it can write an endpoint with a new profile ID before it has written the data for that profile ID.

- One solution would be to set Ready to false at the start of a resync, and to true at the end.  However that might cause a lot of Felix churn, when compared with instead reordering the writes.  

- Also that still leaves the non-resync updates to be looked at.

Thoughts welcome, and also on how highly we should prioritize this.

**Comment by fasaxc** [comment]
Felix explicitly handles out-of-order endpoint/profile updates but it's more efficient to do them in the right order.  (It also avoids flapping because felix's behaviour is to treat a missing profile as if it had a drop all rule.)

The ready flag is a blunt instrument, you should only use it for a bulk resync operation (recreating the etcd database).  In normal usage, you should just leave it set to true and write to etcd normally as data changes.

**Comment by neiljerram** [comment]
Thanks @fasaxc.  Possibly, then, the plugin code is already correct.  But I should do a more careful review - will leave this issue open so as to track that.

**Comment by fasaxc** [comment]
The key thing we _don't_ want to do is set the Ready flag too early when etcd gets blown away and we spot we need to resync.

**Comment by ed-harrison** [comment]
@neiljerram As we are getting closer to v1.0 can we get an updated view on whether you think this is still an issue?

**Comment by neiljerram** [comment]
My guess is that we're close enough now to call this done for 1.0.  @Lukasa fixed the biggest problem as part of the HA rewrite, i.e. calling provide_felix_config() at the _end_ of the resync processing, instead of at the _beginning_.

**Comment by fasaxc** [comment]
@neiljerram what's left to do apart from that?  I think we can close this.

**Comment by neiljerram** [comment]
@fasaxc Nothing specific - but perhaps a careful review of how the plugin processes dynamic port and SG updates, to check that it always updates etcd such that the etcd DB is consistent at every step.

**Comment by Lukasa** [comment]
I think any concerns about processing of port and SG updates are strictly outside the scope of this issue.
