### ISSUE TITLE
Reinstate felix's ability to specify config file path

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#329]
We used to use argparse to accept a --config-file option but we lost that when we moved to python 2.6 (at least on the etcd branch).  We should reinstate that by using optparse (or decide it's not needed).

**Comment by Lukasa** [comment]
This needs an assignee.

**Comment by Lukasa** [comment]
This has been languishing, but is reasonably important, so I'm moving to 0.18.

**Comment by neiljerram** [comment]
@plwhite Would you like to include this in your config work too?  It's not strictly the same, so I'd equally be happy not to do that (and then probably leave it until after 0.18).  What do you think?

**Comment by plwhite** [comment]
Fix with Cory to review, so passing ownership to him.
