### ISSUE TITLE
Don't stub out chains during "graceful restart" window

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#339]
Currently, if the endpoints, dispatch chains and profile rules don't all feed their config into the IptablesUpdater before it does its first update then it'll stub out chains that may still be valid.  I propose that we add a grace period at start of day where we don't stub out any chain that already exists and instead we wait until the first call to cleanup() to stub out any chains we've not heard of yet.

**Comment by Lukasa** [comment]
This needs an assignee.

**Comment by Lukasa** [comment]
@ed-harrison You assigned this to 0.17 but without anyone having a direct action to fix it. Can you please either assign someone the issue or move it out to 0.18?

**Comment by ed-harrison** [comment]
TBH I don't know whether this is important enough for 0.17 (and I'm not even sure why I touched it in the first place last week!).  For now, let's move it to 1.0, but assign it to Shaun who can decide whether it is more urgent than this.

**Comment by lxpollitt** [comment]
I think @fasaxc  is the right person to triage this and judge when it needs to be fixed (and probably be the person that fixes it).  I'm wondering if for example if this will be hit regularly by Piston when they move etcd around frequently, which would make it higher priority.

**Comment by plwhite** [comment]
While we might do something tactical here, there's also a discussion of the cleanup code where I had some ideas for tidying it up and simplifying it (see the Felix design ideas doc). Those ideas might be nonsense, but if they aren't then this might go away.

That implies pushing it out until next week unless there's real pressure to fix in the short term (and my guess is that it is unlikely to happen in real life, but it's a timing thing which means that it's impossible to be sure).

**Comment by plwhite** [comment]
I have a radical alternative to this. We should : 

* Remove the 30 second sleep before cleanup, and do it right away. I put a proposal for how I think we should do this in google docs.
* Never stub out chains unless they are either explicitly deleted, or are created to satisfy a dependency.

If we can get this idea to fly, I think it potentially makes resolving this issue trivial.
