### ISSUE TITLE
We should rationalise our configuration story

### ISSUE THREAD

**Issue by plwhite** [Metaswitch/calico#34]
Two related issues.

* For Felix (and no doubt similarly in the ACL Manager and Plugin), the configuration is stored in multiple places. In Felix, those are the config file checked into the Calico repository; the config file checked into the chef repository; and the code itself. That means three places to comment the legal values, and three places for default values to be placed. That is confusing and messy.

* Felix, the ACL Manager and the Plugin all have related configuration. For example, if Felix has a connection timeout of 15 seconds, and the ACL Manager sends keepalives every 30 seconds, then Felix will continually tear down connections and restart them. We should at least document this kind of dependency, and perhaps combine configuration for the two components (so that both Felix and the ACL Manager read the same connection timeout value).

**Comment by matthewdupre** [comment]
Our configuration story is now quite different.  There are still several different sources, but there are good reasons for having them, and the possibility of inconsistent configuration is much reduced.
