### ISSUE TITLE
Felix upstart job uses start-stop-daemon

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#348]
Seems redundant (and possibly wrong) unless I'm missing something.  It's normal to just have the upstart script start the process directly.  Upstart then monitors the started process as a child.  I.e. the child isn't supposed to daemonize itself; upstart forks it off and then monitors it correctly.

**Comment by Lukasa** [comment]
Entirely correct.

**Comment by fasaxc** [comment]
I think this might even prevent felix from restarting after a failure, we should fix.  Assigning to @neiljerram  since he created that file and I want to make sure we're in sync.

**Comment by matthewdupre** [comment]
Have we actually observed Felix not restarting?  I'm confident that it did, so this isn't really a bug at all, just a markup (and therefore definitely not a requirement for 0.16).

**Comment by fasaxc** [comment]
I have seen it not get restarted even though I don't think that upstart stops retrying; I'm not sure of the precise circumstances that need to occur though.  I have seen it restarted too.

**Comment by neiljerram** [comment]
I think there was a recent steer from @lxpollitt not to fix things that aren't broken....  So I'm inclined just to close this with no action.
