### ISSUE TITLE
Felix should canonicalise IP addresses

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#357]
I didn't use netaddr in the felix code for fear of exploding our occupancy.  However, that leaves a gap, particularly for IPv6, where we might treat different spellings of the same address as a different address.

We could do this somewhere between the etcd layer and the update splitter.

**Comment by neiljerram** [comment]
Doesn't seem urgent to me, and we have loads to do for 0.17, so moving this out to 0.18.

**Comment by lxpollitt** [comment]
If this is trivial to fix and won't measurably impact Felix occupancy then it probably does make sense to address by 1.0, though it doesn't feel super urgent.  If it isn't trivial or measurably impacts occupancy then I think we should consider whether we can just document a canonical form in our etcd data model and ensure that the OpenStack plug-in and calicoctl honor that for 1.0.

**Comment by fasaxc** [comment]
Fixed under #568.  #229 tracks switching to IPAddress/IPNetwork objects but that's less important IMO.
