### ISSUE TITLE
Nova gives nics in non-deterministic order

### ISSUE THREAD

**Issue by alexaltair** [Metaswitch/calico#373]
In the FV testing, I've instantiated a VM in OpenStack with multiple networks attached. Only one of these interfaces will be up to begin with. In order to find which interface to use to connect to this VM, I call `vm.interface_list` (part of the [python-novaclient](https://github.com/openstack/python-novaclient/blob/master/novaclient/v2/servers.py) API). This returns a list of two JSON-like data structures, representing the interfaces. The problem is that 1) they don't contain any information about which one is eth0 and which is eth1 and 2) the order is non-deterministic.

I ended up using a different strategy to solve my problem, but this looks like a [known bug in nova](https://bugs.launchpad.net/nova/+bug/1300325). The link claims it to be fixed in 2014.1; we're using nova version 2014.1.3, but the behavior remains. Since we're patching nova, maybe we should base it off a newer version?

**Comment by Lukasa** [comment]
It looks to me like, if this is still being hit, it's a bug that needs reporting upstream.

More generally, while we patch nova we are trying not to be in the business of backporting bugfixes unless absolutely necessary. That means we take whatever release ubuntu shipped and apply our patches on top, which greatly simplifies the packaging process. I'd be pretty strongly disinclined to backport any fix for this issue unless it was absolutely necessary.

**Comment by neiljerram** [comment]
The fix for https://bugs.launchpad.net/nova/+bug/1300325 is definitely in the Nova code that we use on Ubuntu/Icehouse.  (I.e. in the calico_2014.1.3 branch of https://github.com/Metaswitch/calico-nova.)  So there must be a different cause of the non-deterministic order that you were seeing.
