### ISSUE TITLE
Neutron plugin writes endpoints without a workload_id in the key

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#386]
Spotted while adding the '/v1/' prefix into the data model.  The plugin is writing keys like this:

`/calico/v1/host/felix-host-1/workload/openstack/endpoint/DEADBEEF-1234-5678`

which is missing the workload_id:

`/calico/v1/host/felix-host-1/workload/openstack/<workload_id>/endpoint/DEADBEEF-1234-5678`

As a work-around to let me make progress, I've inserted the endpoint ID in that place in the URL but this is wrong! (Or I will have when I push my changes shortly.)

Currently, there is no impact because Felix ignores this value.  However, this might not always be the case, especially if we need to relax our anti-spoofing rules.

**Comment by neiljerram** [comment]
I appreciate that this is wrong according to the data model.  However, what do you need a workaround for, if (as you say) Felix ignores the value?

**Comment by fasaxc** [comment]
@neiljerram I thought it was crazy to do the work to add /v1/ to the keys without making the key-calculation logic common between felix and the neutron plugin so I made a new module to contain the keys and functions to calculate keys for different things.  Since there's now an API there, it needs a `workload_id` passed in to calculate the key.  Seemed silly to move the bug into the common code rather than keeping it in the plugin.

**Comment by fasaxc** [comment]
Pull request for the version change is here: https://github.com/Metaswitch/calico/pull/387 if you want to see what I'm talking about.

**Comment by fasaxc** [comment]
I think we should fix this up in the next release if possible to avoid the need to migrate.

**Comment by Lukasa** [comment]
The actual bug originally reported is now fixed, so I'm closing this. There's a separate enhancement, which I'm tracking in #445.
