### ISSUE TITLE
Bird logs spammed with "<WARN> Netlink: File exists"

### ISSUE THREAD

**Issue by Symmetric** [Metaswitch/calico#388]
The bird logs are spammed with this sort of thing:

```
2015-04-16 20:32:47 <WARN> Netlink: File exists
2015-04-16 20:32:47 <WARN> Netlink: File exists
2015-04-16 20:32:49 <WARN> Netlink: File exists
2015-04-16 20:32:49 <WARN> Netlink: File exists
2015-04-16 20:32:51 <WARN> Netlink: File exists
2015-04-16 20:32:51 <WARN> ...
```

This makes it harder to spot actual issues, and nearly impossible to get a good feel for the general flow of BGP messages. 

(Of course, you can do `grep -v 'Netlink\|\.\.\.' bird.log`, but that's not very user-friendly)

**Comment by fasaxc** [comment]
This looks like a bug in our BIRD config: https://gitlab.labs.nic.cz/labs/bird/wikis/FAQ#netlink-file-exists

We should set BIRD to prefer kernel routes.  @Symmetric do you have a system exhibiting the issue that you can try the fix out on?

**Comment by Symmetric** [comment]
@fasaxc yep, looks like it's still occurring on my dev machine.

**Comment by ed-harrison** [comment]
@matthewdupre Can you have a look at this - I think some of the comments in https://gitlab.labs.nic.cz/labs/bird/wikis/FAQ#netlink-file-exists may relate to the conversation we've been having about route preference anyway.

**Comment by matthewdupre** [comment]
This is being caused by BIRD trying to reinstall the host's interface subnet routes (e.g. 172.18.203.0/24 for most of ours).

**Comment by matthewdupre** [comment]
Fixed.
