### ISSUE TITLE
Felix implicitly assume rules from ACL Manager have a DENY default

### ISSUE THREAD

**Issue by plwhite** [Metaswitch/calico#39]
Specifically, it assumes that ACL manager is giving it default allow rules for outbound, and deny rules for inbound. That is not always true. We need to fix that assumption.

**Comment by matthewdupre** [comment]
ACL Manager currently asserts that all rules have a DENY default.

There will always be limitations in this area - the main problem is that the defaults are provided to ACL Manager scoped to a group, and an endpoint may be in multiple groups, which leads to the question: how do you resolve conflicting defaults for a single endpoint?

A pragmatic approach will be needed based on real use cases.

**Comment by plwhite** [comment]
Superseded by PR #307.
