### ISSUE TITLE
Need to update deb manifests to depend on custom python-etcd version

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#392]
We tried a chef install and it didn't get picked up.

I think this needs to be resolved for the release.  I wasn't sure how to update the manifest file (there are version macros etc that I wasn't sure how to use).

**Comment by ed-harrison** [comment]
@matthewdupre Is this now resolved?

**Comment by fasaxc** [comment]
@robbrockbank Please can you look out for this on your new test run from master?

**Comment by Lukasa** [comment]
Regardless of whether we're hitting this or not, we should be doing this right.

**Comment by Lukasa** [comment]
See #412.
