### ISSUE TITLE
Calico configuration is not documented in the etcd-data-model document

### ISSUE THREAD

**Issue by ed-harrison** [Metaswitch/calico#402]
calico/docs/source/etcd-data-model.rst (currently in branch etcd-docs) contains placeholder text for the Calico configuration.  This document needs to be updated to include Calico config keys and should also be referred to from configuration.rst.

**Comment by matthewdupre** [comment]
The Felix config file options are documented, but the other etcd stored configuration isn't yet.

**Comment by Lukasa** [comment]
Felix doesn't take a config file, so at the very least these need to be updated to point at the etcd keys.

**Comment by plwhite** [comment]
Yes it does. However, the config file contains only the fields required for Felix to read the data from etcd (i.e. the etcd port and IP, and the name of this Felix - both of which default, to "localhost:4001" and the local hostname respectively).

**Comment by Lukasa** [comment]
Ah, yes, sorry.

I retract my obvious silliness. :rocket:

**Comment by lxpollitt** [comment]
For 0.16 I think these could remain undocumented (since 0.16 is aimed at OpenStack deployments primarily and we do not expect/require OpenStack users to write anything into etcd directly themselves under normal operation).  We should then make sure we document them for 0.17 in line with wherever we get to on #407.

**Comment by matthewdupre** [comment]
Yes, I'm going to push this out to 0.17, where it can be resolved according to the agreed fix to #407.

**Comment by neiljerram** [comment]
@matthewdupre Are you planning to do the work here, for 0.17?

**Comment by ed-harrison** [comment]
I think there is a more general question first about what the config model is (i.e. as per #407).

**Comment by neiljerram** [comment]
@plwhite - I think this is part of your config file work, too.  (Sorry!)
