### ISSUE TITLE
Make plugin fully robust to etcd disappearance/replacement.

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#405]
Neil, I think you said there were still some threads to pull on to make the plugin fully robust to etcd disappearing/reappearing.

We should continue beefing this up for the customer who requires it.  I'll add it to the list of planned automated FVs for the bobcats to pick up.

**Comment by matthewdupre** [comment]
@Lukasa @neiljerram Do you think this is still a problem since the Neutron HA work?

**Comment by Lukasa** [comment]
I *believe* we're ok, but we really should test it.

**Comment by fasaxc** [comment]
@matthewdupre I think we should beat on this before 1.0

**Comment by matthewdupre** [comment]
That sounds sensible, but we shouldn't be tracking generic testing using issues.

There's no specific issue we know of here, so @lwr20  could you please check this is in the test plan and then close the issue.

**Comment by lwr20** [comment]
It *is* in the test plan, but likely not in 1.0 at this point.  

@fasaxc can you talk to @ed-harrison if you need this prioritised please?

**Comment by Lukasa** [comment]
Given that this is in the test plan, I'm closing this.
