### ISSUE TITLE
Lift python-etcd urllib3 <1.8 restriction?

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#419]
I put this in because, when I tried python-etcd with a newer build of urllib3, python-etcd wasn't ready to handle the new exceptions in the new urllib3 versions.  For example, ProtocolError, was added in 1.8.  this interfered with python-etcd's multi-node support 

OTOH, urllib3 1.10 is the current version, and it has a lot of bugfixes and improvements.

**Comment by fasaxc** [comment]
Lifting the restriction is made more difficult if we need to support 1.7.1 too.  It's not trivial to catch an exception for 1.8+ that doesn't exist in 1.7.1 since we won't be able to import the exception normally in 1.7.1.

**Comment by Lukasa** [comment]
Lifting this restriction in general is a massive PITA on Ubuntu 14.04, because *lots* of system packages have a dependency on `python-urllib3` at the current version. It'll essentially require us either to vendor (do-able) or deploy a virtualenv in prod.

**Comment by fasaxc** [comment]
@Lukasa I was thinking we'd have to make python-etcd work with whichever version was installed: 1.7.1 or 1.10.x.  Then, those who would like to use a newer distribution of urllib3 (I think @nbartos falls in this camp) can run with that, even if, on stock Ubuntu, we'd use 1.7.1.

**Comment by Lukasa** [comment]
That's plausible, but I suspect it'll be quite painful. urllib3 has changed a lot between 1.7 and 1.10. Still, worth looking into.

**Comment by Lukasa** [comment]
This needs an assignee.

**Comment by neiljerram** [comment]
Deferring to 1.0, but I think we should actually close this until we have a reason to move to >= 1.8.  Any objections to that?

**Comment by ed-harrison** [comment]
@Lukasa You asked for an asignee, so can you work out whether you're the right person to address Neil's "shall we close this" question?

**Comment by Lukasa** [comment]
I don't think we want to move to 1.8 because of the logistical problems of doing so. If we didn't have those problems I think it'd be fine, but we do, so I'm inclined to want to stay where we are at this time. @fasaxc, do you believe there's a compelling reason to move that outweighs that cost?

**Comment by fasaxc** [comment]
@Lukasa I wasn't thinking that we'd require 1.8+, just that we should make sure that python-etcd and/or our code supports it properly.

Actually, we might already be "good enough" in this regard even if python-etcd doesn't have good support for the new urllib3 versions.  We now catch the base exception types from `urllib3`, `httplib` and `socket` and trigger a full reconnection.  Hard to see how anything could get past that.

**Comment by eepyaich** [comment]
Given the latest comment from @fasaxc, can we close this @Lukasa?

**Comment by Lukasa** [comment]
Yup. =)
