### ISSUE TITLE
Felix logging goes to stdout/err (at least until we load config)

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#422]
The default_logging() function installs a global StreamHandler that logs to stdout.  I think this is causing issues for @nbartos at Piston Cloud; he wants to be able to suppress all logging apart from syslog and, at least until we conenct to etcd, we're logging to stdout.

**Comment by fasaxc** [comment]
Nick also found a case where gevent is logging directly to stderr, from it's hub.py.  It simply writes directly to stderr if a greenlet dies with an exception.

**Comment by Lukasa** [comment]
Log levels should be configurable, they always used to be.

**Comment by fasaxc** [comment]
I think that'd be good enough as long as we don't log anything to stdout/err in the mainline case where everything is working.

**Comment by DaveLangridge** [comment]
On RHEL 7.1 all the felix logs are going to messages.

**Comment by DaveLangridge** [comment]
Ignore the above. They're now going to /var/log/calico/felix.log as expected.

**Comment by neiljerram** [comment]
@plwhite Can you look at covering this in your config file work?

**Comment by plwhite** [comment]
My fix just means that if you have a config file turning down log levels, or use the env variable FELIX_LOGSEVERITYSCREEN to critical, then there is no logging to screen.
