### ISSUE TITLE
Support wildcarded ICMP type with fixed ICMP code

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#424]
I believe OpenStack supports matching on ICMP code without matching on ICMP type but iptables doesn't seem to support this natively.  #421 adds support for matching on ICMP code but it requires a type to be specified (enforced at felix validation time).  This issue tracks adding support for wildcarded type with ICMP code specified.

We might do that by:

* Installing a rule for every ICMP type and the given code.  This is simple but required 255 rules.
* Rejecting the case in the neutron plugin and reporting an error.
* Using an ipset.

Using an ipset would be complex and we'd still have to program in all the combinations.  I vote for one of the first two.  I don't think it'd be crazy to reject this case or to program lots of rules because specifying a code without a type is a very weird thing to do (since the valid codes are dependent on the type); it's almost certainly a misconfiguration.

**Comment by fasaxc** [comment]
iptables documentation:

```
   icmp (IPv4-specific)
       This extension can be used if `--protocol icmp' is specified. It provides the following option:

       [!] --icmp-type {type[/code]|typename}
              This allows specification of the ICMP type, which can be a numeric ICMP type, type/code pair, or one of the ICMP type names shown by the command
               iptables -p icmp -h

```

**Comment by fasaxc** [comment]
Another option:  we could use the u32 iptables match to match on the bytes in the right position.  would need some more thought but this would do it in a single rule.

**Comment by fasaxc** [comment]
Not pretty but one the u32 examples is for matching the ICMP type, which is only one byte over from the code:

```
       Example: (more realistic, hence more complicated)

              match ICMP packets with icmp type 0

              First test that it is an ICMP packet, true iff byte 9 (protocol) = 1

              --u32 "6 & 0xFF = 1 && ...

              read bytes 6-9, use & to throw away bytes 6-8 and compare the result to 1. Next test that it is not a fragment. (If so, it might be part of such a packet but  we  cannot  always  tell.)
              N.B.: This test is generally needed if you want to match anything beyond the IP header. The last 6 bits of byte 6 and all of byte 7 are 0 iff this is a complete packet (not a fragment).
              Alternatively, you can allow first fragments by only testing the last 5 bits of byte 6.

               ... 4 & 0x3FFF = 0 && ...

              Last test: the first byte past the IP header (the type) is 0. This is where we have to use the @syntax. The length of the IP header (IHL) in 32 bit words is stored in the right half  of
              byte 0 of the IP header itself.

               ... 0 >> 22 & 0x3C @ 0 >> 24 = 0"

              The  first  0  means read bytes 0-3, >>22 means shift that 22 bits to the right. Shifting 24 bits would give the first byte, so only 22 bits is four times that plus a few more bits. &3C
              then eliminates the two extra bits on the right and the first four bits of the first byte. For instance, if IHL=5, then the IP header is 20 (4 x 5) bytes long. In this case,  bytes  0-1
              are  (in binary) xxxx0101 yyzzzzzz, >>22 gives the 10 bit value xxxx0101yy and &3C gives 010100. @ means to use this number as a new offset into the packet, and read four bytes starting
              from there. This is the first 4 bytes of the ICMP payload, of which byte 0 is the ICMP type. Therefore, we simply shift the value 24 to the right to throw out all but the first byte and
              compare the result with 0.

```

**Comment by neiljerram** [comment]
Is this practically important enough for our next release?

**Comment by neiljerram** [comment]
Does it actually make any sense to match on ICMP code but not type?  From http://www.nthelp.com/icmp.html it looks clear to me that the answer to that is no.  Hence deferring this to 1.0 - but in fact might not even be important for MVP.

**Comment by fasaxc** [comment]
I think that's fine.  It does make no sense; but that doesn't mean no-one will do it!

**Comment by fasaxc** [comment]
Investigated this and found that Openstack does not allow either "-1" or an empty string for the type when a code is specified.  Horizon gives an error when I try that.

Tested that on Ubuntu, version: 2014.1.4-0ubuntu2calico0.18.2

**Comment by fasaxc** [comment]
@DaveLangridge do you have a 2014.2.2 deployment handy?  If so, please can you check that Horizon rejects an ICMP rule with only a code and no type?  (It's worth trying "-1" and "" for the type.)

If it's the same on the more recent version then I think we can just close this out.

**Comment by DaveLangridge** [comment]
I only have kilo sytems. A code with no type is rejected on these. I agree that this can be closed.

**Comment by matthewdupre** [comment]
Sounds like this isn't possible - closing it.
