### ISSUE TITLE
python-etcd cluster ID check interacts with reconnect processing

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#425]
Our version of python-etcd now checks the cluster ID to make sure we don't start a poll against a different cluster than we read the original data from (sicne the polling indexes will be wrong).  However, our reconnect processing (added to work around an urllib3 issue with reusing a connection) interacts with this: it tears down the python-etcd Client, resetting the cluster ID.

**Comment by neiljerram** [comment]
Does the requirement here conflict with https://github.com/Metaswitch/calico/issues/438?  Sounds to me like it might do.

**Comment by fasaxc** [comment]
Yes @neiljerram it does, however, I thought I'd already fixed that under an update.  With me to unpick.

**Comment by fasaxc** [comment]
#426 addresses this.
