### ISSUE TITLE
Handle migrating endpoint keeping same UUID

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#439]
felix assumes that an endpoint's ID belongs to a particular host.   However, during a migration, endpoints keep their ID while moving between hosts.

As long as the plugin deletes the old etcd endpoint before creating the new, this should work fine.  However, if the ordering gets inverted, felix may update its indexes incorrectly.  In particular, if felix sees:

* add host-A/endpoint-1
* add host-B/endpoint-1
* delete host-A/endpoint-1

then it will delete host-B/endpoint-1 from its index by mistake.

Suggest we fix up this case in felix, even if the plugin is behaving correctly.

**Comment by fasaxc** [comment]
@neiljerram will the plugin do the right thing in the mainline case of a migration (delete the old endpoint before adding the new)?

If so, there are still a couple of corner cases to cover but we can definitely defer this to 0.18.

**Comment by neiljerram** [comment]
Yes, it deletes on the old host before creating on the new one.  So deferring to 0.18 as you've suggested.

**Comment by neiljerram** [comment]
Deferring further, for same reason as previous deferral.
