### ISSUE TITLE
Need to bump etcd version in our PPA

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#444]
We're shipping 2.0.0 but 2.0.9, at least, fixes some bugs around recursive waits.  We should bump our version.

**Comment by fasaxc** [comment]
Background: retesting #426, I found that, when testing with a proxy in place, sometimes the proxy fails to respond to watches at all after the central cluster has been replaced.  It doesn't even return the headers, which etcd normally does immediately.

It's possible that 2.0.9 wouldn't fix this but they'll tell us to go away if we don't rev the version we're using first.

**Comment by fasaxc** [comment]
@Lukasa any chance of getting a 2.0.9 package to test with tomorrow?

**Comment by Lukasa** [comment]
@fasaxc Nope.

Revving the package version is a non-trivial task, sadly, and I have almost no time this week to do it. In the meantime I recommend downloading the 2.0.9 etcd binaries by hand, blatting them over the ones the package installed, and testing with them. That should be enough to confirm whether the problem exists or not.

**Comment by fasaxc** [comment]
2.0.10 is now out with some more, important-sounding bug fixes.

**Comment by neiljerram** [comment]
@Lukasa Do you have time in plan for this, this sprint?  I'm not saying you should do; just asking...  Do you have an estimate for how much time it would take?

**Comment by Lukasa** [comment]
I do not have time in plan for this.

Approx 3/4 of a day, I suspect.

**Comment by neiljerram** [comment]
Thanks, @Lukasa.  I'll defer this to 1.0, then, until/unless we have a clearer reason for needing something in a more recent etcd release.

**Comment by fasaxc** [comment]
2.0.0 is definitely broken for recursive watches, which is exactly what we do.  The symptom is felix fails to get updates, which makes Calico look unreliable.  I think we need to rev to at least 2.0.9 or change the install instructions to use the tarball for now.

**Comment by Lukasa** [comment]
@fasaxc And we've verified that 2.0.9 does not have this problem?

**Comment by fasaxc** [comment]
We've definitely seen the pre-2.0.9 recursive watch issues in the past.  I haven't verified that 2.0.9 solves the proxy-with-cluster-rebuild issue but that's not too pressing.  Piston (who are the only ones I expect to hit the rebuild issues on a regular basis) are using 2.0.9 and they're not using a proxy.

**Comment by matthewdupre** [comment]
Moved to 2.0.11 several weeks ago.
