### ISSUE TITLE
Enhance plugin to set the etcd workload ID to the instance ID, not the endpoint ID

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico#445]
Following on from #386, we'd like to round out the plugin so that it writes the instance ID as the etcd workload ID. Currently it writes the endpoint ID, which leads to some weird redundancy in the key.

**Comment by neiljerram** [comment]
I believe this will become practically important when we start allowing a workload to send from any of its IP addresses through any of its endpoint ports - but for now that is still work in progress.  Hence moving this out to 1.0.

**Comment by lxpollitt** [comment]
Will this change mean that any workload data already in etcd would need migrating?  If so then we either need to fix before our first customer goes GA or we need to commit to writing code to handle the upgrades.  My guess is we should therefore fix this for 0.18.  @neiljerram please confirm.
