### ISSUE TITLE
Plugin does not clear up etcd keys

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico#446]
Sadly, the plugin appears to leave empty etcd keys around. The deployment below has only ever had 4 VMs on it, but it has a ton of redundant key information:

```
ubuntu@calico-vm15:~$ etcdctl ls /calico --recursive
/calico/v1
/calico/v1/host
/calico/v1/host/calico-vm13
/calico/v1/host/calico-vm13/workload
/calico/v1/host/calico-vm13/workload/openstack
/calico/v1/host/calico-vm13/workload/openstack/0a58d2ad-b356-49e2-85d0-6f68a60ebac5
/calico/v1/host/calico-vm13/workload/openstack/0a58d2ad-b356-49e2-85d0-6f68a60ebac5/endpoint
/calico/v1/host/calico-vm13/workload/openstack/0a58d2ad-b356-49e2-85d0-6f68a60ebac5/endpoint/0a58d2ad-b356-49e2-85d0-6f68a60ebac5
/calico/v1/host/calico-vm13/workload/openstack/137bb978-3bd1-449b-9b8f-9d2a5a1608e1
/calico/v1/host/calico-vm13/workload/openstack/137bb978-3bd1-449b-9b8f-9d2a5a1608e1/endpoint
/calico/v1/host/calico-vm13/workload/openstack/137bb978-3bd1-449b-9b8f-9d2a5a1608e1/endpoint/137bb978-3bd1-449b-9b8f-9d2a5a1608e1
/calico/v1/host/calico-vm13/workload/openstack/2072ec1f-3c2b-4ff2-ba92-cae054c626ac
/calico/v1/host/calico-vm13/workload/openstack/2072ec1f-3c2b-4ff2-ba92-cae054c626ac/endpoint
/calico/v1/host/calico-vm13/workload/openstack/aed8d0f5-07a1-4f8a-944a-dcd13ae1b838
/calico/v1/host/calico-vm13/workload/openstack/aed8d0f5-07a1-4f8a-944a-dcd13ae1b838/endpoint
/calico/v1/host/calico-vm13/workload/openstack/aed8d0f5-07a1-4f8a-944a-dcd13ae1b838/endpoint/aed8d0f5-07a1-4f8a-944a-dcd13ae1b838
/calico/v1/host/calico-vm15
/calico/v1/host/calico-vm15/workload
/calico/v1/host/calico-vm15/workload/openstack
/calico/v1/host/calico-vm15/workload/openstack/fd295fab-f0ab-464d-985e-d7811d794219
/calico/v1/host/calico-vm15/workload/openstack/fd295fab-f0ab-464d-985e-d7811d794219/endpoint
/calico/v1/host/calico-vm15/workload/openstack/ee234bca-4980-4ea6-ae14-fa47e9a2a8cc
/calico/v1/host/calico-vm15/workload/openstack/ee234bca-4980-4ea6-ae14-fa47e9a2a8cc/endpoint
/calico/v1/host/calico-vm15/workload/openstack/a85df773-681a-4891-90c1-e0ee30614d2f
/calico/v1/host/calico-vm15/workload/openstack/a85df773-681a-4891-90c1-e0ee30614d2f/endpoint
/calico/v1/host/calico-vm15/workload/openstack/a85df773-681a-4891-90c1-e0ee30614d2f/endpoint/a85df773-681a-4891-90c1-e0ee30614d2f
/calico/v1/policy
/calico/v1/policy/profile
/calico/v1/policy/profile/08c1346b-09d4-468e-a077-0812a7bb8eac
/calico/v1/policy/profile/08c1346b-09d4-468e-a077-0812a7bb8eac/rules
/calico/v1/policy/profile/08c1346b-09d4-468e-a077-0812a7bb8eac/tags
/calico/v1/config
/calico/v1/config/InterfacePrefix
/calico/v1/Ready
```

This is probably because the plugin doesn't delete newly-empty keys. This of course means they'll never get deleted and instead will hang around for all time, slowly contributing to the ever increasing entropy of the universe as we run out of bytes in which we can store our data, thereby ever so slightly bringing forward the date of the eventual heat death of the universe.

We should fix this, is what I'm saying.

![](http://www.porkfist.com/images/heat-death_notice.jpg)

**Comment by fasaxc** [comment]
We should copuple this with felix test and fix to ensure it correctly handles the deletion of the relevant directories directories.  In particular, I don't think felix can handle a whole host being deleted without a resync right now because it lacks the relevant index to calculate which endpoints went away  (even if there were no endpoints on that host).

**Comment by neiljerram** [comment]
@Lukasa Are you sure that leaving the keys there will definitely increase entropy more than deleting them?

**Comment by fasaxc** [comment]
I think this is causing real-world issues for one of our customer's trials.  They're doing heavy churn testing so they'll be building up a lot of old keys.

**Comment by fasaxc** [comment]
WiP on felix changes to handle dir delete on branch smc-handle-dir-delete

**Comment by neiljerram** [comment]
Thanks @fasaxc, but I'm afraid there's no practical chance of getting this done for 0.18.

**Comment by fasaxc** [comment]
@neiljerram  Understood.  I think the plugin work is very staightforward because etcd has a "delete dir if not empty" operation we can use but the felix side needs more work.

**Comment by matthewdupre** [comment]
@fasaxc has a fix to this been merged?  There are a whole bunch of pull requests that all say 'work continued in <other place>'.

**Comment by matthewdupre** [comment]
Never mind, I found it - it went into #548.
