### ISSUE TITLE
RHEL 7.1 install issues

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#454]
Running through an install on RHEL 7.1, I hit these issues:

* ~~Step 1: delete networks.  I was unable to delete the lone public network (no routers or VMs were present).  Horizon showed a little error balloon.  Not obvious if the public network is special or if this was a problem.~~

Edit: cross out updates that we've already made.

**Comment by fasaxc** [comment]
Step 8 uses wget (which wasn't installed by default).  Other steps used curl.

**Comment by fasaxc** [comment]
Compute node step 1: Not clear if the instructions are telling me to read the lib virt link and do that before I continue, or, this step summarises the linked resource so I don't need to.

**Comment by fasaxc** [comment]
Compute node instructions missing this line: 
yum install python-devel libffi-devel openssl-devel

**Comment by fasaxc** [comment]
ETCD_LISTEN_CLIENT_URLS for the proxy setup should include the http://0.0.0.0:2379 entry (or etcdctl doesn't work for debugging)

**Comment by DaveLangridge** [comment]
I also notices that the last compute node step had gone. I know we're debating the config file stuff, but you still need to start calico-felix. Was:
12.	Create the /etc/calico/felix.cfg file by copying /etc/calico/felix.cfg.example and edit it:
•	Change the PluginAddress and ACLAddress settings to the host name or IP address of the controller node.
•	Restart the Felix service:
•	on RHEL 6.5, run initctl start calico-felix.
•	on RHEL 7, run systemctl restart calico-felix.

**Comment by fasaxc** [comment]
*Removed the curl issue from my first comment, it was down to the system clock being wrong

**Comment by Lukasa** [comment]
> Step 1: delete networks. I was unable to delete the lone public network (no routers or VMs were present). Horizon showed a little error balloon. Not obvious if the public network is special or if this was a problem.

This step doesn't just concern itself with routers/VMs. You also need to get rid of subnets.

Additionally, you must be the admin tenant for this, and if you're doing Horizon stuff you also need to make sure you're in the 'admin' pane, not the 'project' pane.

Finally, it would probably have helped to write down what error you say from Horizon. :wink:

**Comment by fasaxc** [comment]
etcd ram disk mount point is different to the directory we give to etcd itself

**Comment by fasaxc** [comment]
cluster ID needs to be different on each start of etcd

**Comment by fasaxc** [comment]
@Lukasa it was your typical Horizon "red balloon".  Absolutely no detail whatsoever!

**Comment by fasaxc** [comment]
Neutron network gateway needs to be distinct from real gateway => use distinct compute host and VM IP ranges even in testing.  When defining the IP pool networks and subnets, the docs say "gateway" without qualification.  It's not clear whether that's the upstream gateway or a made-up virtual gateway.  We accidentally re-used the real physical gateway address for the subnet and that ended up shadowing it.  (It should be a made-up address, within the subnet.)

**Comment by fasaxc** [comment]
Need to tell people to turn off any other networking agents they're running.  for example, the Linux bridge agent.

**Comment by fasaxc** [comment]
We use servicectl to disable services, how does this interact with the nova agent add/delete commands?

**Comment by neiljerram** [comment]
@fasaxc What was the way that you used - successfully - to 'turn off' the Linux bridge agent?

**Comment by neiljerram** [comment]
@DaveLangridge @plwhite - Regarding the fact that felix.cfg is currently required in order for Felix to start up...

- Firstly, sorry for missing this for the 0.17 release.  I noticed that diff in the docs between 0.16 and 0.17 (i.e. removing that step from the RHEL install docs) but thought it was OK - because I had forgotten that the startup scripts required it, and because of the following point...

- The situation has, however, substantively changed, in that felix.cfg was previously absolutely required, because it provided configuration that Felix needed and that could not reasonably be defaulted; whereas now all of Felix's configuration _does_ have reasonable defaults, and felix.cfg is only used to override where necessary - and so it's likely that a deployment could run fine without any felix.cfg files.

Therefore I suggest that we probably should remove the requirement (in the startup scripts) for felix.cfg to exist, and correspondingly adapt the install instruction steps.  Thoughts?

**Comment by DaveLangridge** [comment]
If felix only reads the file if it's there, and doesn't barf if it isn't, then removing the copy is fine. As long as we get to start felix somewhere.

**Comment by matthewdupre** [comment]
I'd be happy with anything that removed the manual install step (it was only reinstated as a temporary fix anyway).

I'd probably prefer changing the packages to install felix.cfg directly (not as .example) - it'll work in most cases, so there's no need to push people away, and I think that (in the rare case it's needed) it'll be easier for people to edit if it's already there.  No str

**Comment by fasaxc** [comment]
@neiljerram I'm not sure how the Salesforce folks turned off the bridged agent.  The command went by too fast.  I think they were using some nova commands to delete the agent but I'm not sure if they also disabled it in systemd, for example.

**Comment by fasaxc** [comment]
@neiljerram I'm not sure, the customer made that change.  I saw them run a nova command that deleted the agent but I'm not sure if they also ran a systemd command to disable it.

**Comment by fasaxc** [comment]
I think we have a separate issue tracking the agent-delete addition: #517

**Comment by fasaxc** [comment]
Is there anything left here?

**Comment by DaveLangridge** [comment]
I think they're all fixed now.
