### ISSUE TITLE
Profile character restrictions don't play nicely with Kubernetes naming conventions

### ISSUE THREAD

**Issue by Symmetric** [Metaswitch/calico#459]
We have a pretty restrictive policy naming scheme -- `[a-zA-Z_0-9]`.

Kubernetes happens to not like `_`, and instead uses `-` and sometimes `.`.

Any objection to me relaxing this restriction to include the full set `[_-.]`?

**Comment by lxpollitt** [comment]
+1 (unless someone can spot a reason why this would be a bad idea)

**Comment by Lukasa** [comment]
As long as the value fits in an etcd key I don't see any reason not to. =)

**Comment by fasaxc** [comment]
The characters need to be valid in the name of an iptables chain and an ipset name.  Happy to lift the restriction as long as you check that the new chars are valid.  '-' should be fine, we use that already elsewhere.

**Comment by fasaxc** [comment]
Note, felix isn't validating these right now (#460) but that should change!

**Comment by neiljerram** [comment]
@Symmetric Are you planning to do this fix this week?  For the 0.18 release I'd like to see a code review during my Thursday (=> by end your Wednesday).

**Comment by Symmetric** [comment]
@neiljerram noted. Not sure if I'll get to it by then (I have a high priority demo that I'm working on), but I'll keep you updated.

**Comment by neiljerram** [comment]
Thanks @Symmetric.  I'll remove this from the 0.18 milestone, as it doesn't appear that anyone regards this as clearly urgent on that timescale.  However, of course it would be great if this does get done in time for 0.18 (on Tuesday).

**Comment by Symmetric** [comment]
@neiljerram sounds good, I have demo work that's higher priority and this isn't a blocker.

**Comment by matthewdupre** [comment]
Punting this out to 1.0 - fixing is still with you @Symmetric.

**Comment by lxpollitt** [comment]
@matthewdupre, @Symmetric is out of the office for the next 3 weeks, so I think this should go to someone else.

**Comment by plwhite** [comment]
I do not believe that Felix has this behaviour. It did once, but fixes have gone in since. Hence closing - @Symmetric if you believe I'm wrong please reopen.
