### ISSUE TITLE
Felix should validate profile/endpoint/tag IDs

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#460]
The data model schema defines the valid range of characters but felix doesn't seem to police them.  It should police that only characters that are valid in the data model are used.

Not catastrophic since it is an internal interface but better safe than sorry.

Assigning to Peter as he did a lot of the validation routines (but anyone could take this on).

**Comment by plwhite** [comment]
Actually, I think the right approach here is that for IDs containing any invalid characters, we should just hash them using the uniquely_shorten function (which would then need to be renamed).

**Comment by lxpollitt** [comment]
I vote for just not allowing invalid characters.  Anything else feels like solving a problem we don't yet have.
