### ISSUE TITLE
Fix up alarming logs on failure to delete ipset

### ISSUE THREAD

**Issue by plwhite** [Metaswitch/calico#461]
The following logs get generated on Felix startup.

From Shaun :

"I've gotten to the bottom of the err calico-felix[3639]: actor@255 _finish_msg_batch failed. problem.  The ActiveIpset object that manages the ipset was being asked to add an IP and then told that the ipset was no longer needed.  The cleanup should have aborted the in-flight add operation but it didn't.  Hence, it was recreating the ipset after it should have been gone (and after the new ActiveIpset object had been created).  The 37d9f3e98c4cbb1235847085879d4956ef6ecede patch should be more resilient to his case but it could still bite.  I'll update the fix."

Leads to this error :

    warning calico-felix[5755]: ipsets@328 Failed to delete ipset felix-v6-_c2ef60b0c0c6d17.  
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/site-packages/calico/felix/ipsets.py", line 325, in on_unreferenced
      File "/usr/lib64/python2.7/site-packages/calico/felix/futils.py", line 99, in check_call
    FailedSystemCall: Failed system call (retcode : 1, args : ('ipset', 'destroy', 'felix-v6-_c2ef60b0c0c6d17'))
      stdout  :
      stderr  : ipset v6.21.1: Set cannot be destroyed: it is in use by a kernel component

**Comment by neiljerram** [comment]
@plwhite Agree that this needs to be in 0.18.  Do you have any space for it?

**Comment by fasaxc** [comment]
Is there anything left to fix here?  I think I fixed the underlying issue so we shouldn't hit this case any more (and if we do, we want an error).

**Comment by neiljerram** [comment]
@plwhite Are you happy that this issue is addressed now?  If so, please close.

**Comment by plwhite** [comment]
Fine to close it.
