### ISSUE TITLE
Default BIRD filter is foot-shootingly broad

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#466]
Our default BIRD export filter is to export anything but 0.0.0.0/0.  That means that we export, for example, the routes assigned to the ns-* device that dnsmasq uses.

At the customer trial today, we got bitten by this: they were using a shared subnet for the IP pool and for VM addresses.  When we turned on BIRD, it redistributed the ns-* route and broke networking.

It'd be much safer, in OpenStack, to add a condition on interface name.  We used condition `ifname ~ "tap*"` to resolve the problem.

**Comment by Lukasa** [comment]
Based on some email trails I've seen, @liljenstolpe is actually the one planning to take a swing at this.

**Comment by liljenstolpe** [comment]
I will have a simple fix in today.  We need to think about a cleaner fix, but it probably needs new config-file gen script variables.  When do we want to to discuss that?

**Comment by liljenstolpe** [comment]
Pull request issued to close

**Comment by fasaxc** [comment]
@liljenstolpe have you given this any testing?

**Comment by neiljerram** [comment]
Fixed by #491
