### ISSUE TITLE
Support multiple instances of the Neutron plugin for HA

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#477]
One of our customers wants to roll out multiple plugins for HA purposes (at a scale of ~140 physical servers in the cluster with ~6 control nodes).  I think we need to expedite basic HA support to support that.

It's not essential to have full linear scaling, we just need to support running multiple plugins without multiplying the number of periodic resyncs or clobbering each other's updates.  That could be done through retaking the neutron DB lock, etcd CaS* or even leader-election between the plugins.

*CaS would require minor felix enhancements to treat CaS updates as sets.

I expect this will be difficult to squeeze into 0.18 but perhaps we can land it in 0.19?

**Comment by Lukasa** [comment]
> That could be done through retaking the neutron DB lock, etcd CaS* or even leader-election between the plugins.

To clarify, this almost certainly requires two of those three: probably retaking the neutron DB lock and leader-election.

**Comment by matthewdupre** [comment]
We're going to hold neutron HA until 0.21.

**Comment by matthewdupre** [comment]
This went in last release - closing the issue.
