### ISSUE TITLE
When using etcd as a transient store need to give it a new cluster ID each time

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#478]
Our install guide puts etcd in a ramdisk but we set the initial-cluster-token only at install time.  This is wrong because, each time etcd gets rebuilt in the ramdisk, it will use the same token but it will start with a  fresh etcd index.  That will break felix's watches if it all happens between felix polls.  That's a small window to hit but we should close it.

I've investigated how to do this on RHEL 7.x and it looks like the /etc/sysconfig/etcd does not allow dynamic config so we need to use a wrapper script.

I tried putting this simple wrapper script in usr/local/bin/start-etcd:
```
#!/bin/sh
export ETCD_INITIAL_CLUSTER_TOKEN=`uuidgen`
exec /usr/local/bin/etcd
```
chmodding it +x and then changing the systemd unit file (/usr/lib/systemd/system/etcd.service) to use it:
```
[Unit]
Description=Etcd
After=syslog.target network.target

[Service]
User=root
ExecStart=/usr/local/bin/start-etcd
EnvironmentFile=-/etc/sysconfig/etcd
KillMode=process
Restart=always

[Install]
WantedBy=multi-user.target
```
And I saw it generate anew cluster ID each time.

**Comment by fasaxc** [comment]
Addressed by PR #479.

**Comment by Lukasa** [comment]
Actually this is only partially addressed by #479, because #479 does nothing for Ubuntu.

**Comment by Lukasa** [comment]
Nor does it do anything for RHEL 6.5.

**Comment by fasaxc** [comment]
Yes, sorry, not my clearest comment ever; had the blinkers on.

**Comment by matthewdupre** [comment]
Ubuntu instructions and Chef need updating to match this.
