### ISSUE TITLE
Felix doesn't accept protocol "all" in rules

### ISSUE THREAD

**Issue by Symmetric** [Metaswitch/calico#498]
This is valid in iptables. From the man page:

```
[!] -p, --protocol protocol
The protocol of the rule or of the packet to check. The specified protocol can be one of tcp, udp, udplite, icmp, esp, ah, sctp or the special keyword "all", 
```

The alternative (creating separate rules for TCP and UDP) isn't a dealbreaker, but it's a bit clunky.

**Comment by fasaxc** [comment]
I think Paul has a workaround for the demo he was working on so there's no urgency here but it should be a very straightforward enhancement.

**Comment by Symmetric** [comment]
Yep, low priority at this point.

**Comment by fasaxc** [comment]
I think anyone could pick this up and I'm not going to get to it before my vacation.

**Comment by matthewdupre** [comment]
Related to #608

**Comment by matthewdupre** [comment]
Felix does actually support 'all protocols' rules - you just mustn't specify a protocol at all in etcd.

For example:

`etcdctl get /calico/v1/policy/profile/6fe9fe39-49ce-4a8c-b1ab-1ae4958f60f4/rules
{"outbound_rules": [], "inbound_rules": [{"ip_version": 4, "protocol": "tcp", "src_net": "77.0.0.0/8", "dst_ports": [332]}, {"ip_version": 4, "src_net": "9.0.0.0/8"}]}`

causes Felix to program the following using the 'all' protocol in IPTables:
::
  Chain felix-p-_4e326303dfef501-i (1 references)
   pkts bytes target     prot opt in     out     source               destination
      0     0 RETURN     tcp  --  *      *       77.0.0.0/8           0.0.0.0/0            multiport dports 332
      0     0 RETURN     all  --  *      *       9.0.0.0/8            0.0.0.0/0
      0     0 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* Mark as not matched */ MARK set 0x1

I think this does what you need @Symmetric?
