### ISSUE TITLE
Default notification driver fills up queue without bound

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#512]
The default neutron config (or at least what we use in the FV rig, has this line:
```
notification_driver = neutron.openstack.common.notifier.rpc_notifier
```
That driver pushes notifications onto the notifications.info queue in RabbitMQ.  However, if our defautl configuration, it looks like nothing is draining that queue so it just fills up.

There's a no_op driver that we can use instead or a logging driver.  I'm not really sure what the right one to use is but the one we're using right now in our FV rig is wrong.

**Comment by fasaxc** [comment]
@neiljerram any ideas?

**Comment by fasaxc** [comment]
This non-bug mentions a component that does consume that queue, but apparently we're not running that: https://bugs.launchpad.net/nova/+bug/1188643

**Comment by neiljerram** [comment]
I'll take a look

**Comment by neiljerram** [comment]
Addressed by https://github.com/Metaswitch/calico-chef/pull/26
