### ISSUE TITLE
Exception in felix when deleting port

### ISSUE THREAD

**Issue by DaveLangridge** [Metaswitch/calico#540]
During churn test with felix from neutron-ha branch.

nova/nova-compute.log:2015-05-15 09:53:05.901 1591 ERROR nova.compute.manager [-] [instance: 8e21dcfd-1421-4693-8408-74e77ee28eb2] Build of instance 8e21dcfd-1421-4693-8408-74e77ee28eb2 aborted: Failed to allocate the network(s), not rescheduling.

**Comment by Lukasa** [comment]
This is unrelated to Felix, it's a neutron problem, and should be resolved in 066712521b476c96c517fcbcb1688219823fdd9d.
