### ISSUE TITLE
MAC address update to endpoint is not reflected in ARP cache

### ISSUE THREAD

**Issue by robbrockbank** [Metaswitch/calico#549]
Running with docker containers, a stopped container tears down all interfaces - restarting the container requires new interfaces to be created resulting in different endpoint MACs.

The new MAC address is not being applied to the ARP cache in Felix.

I updated the following code in Felix to test out a quick change to ensure we always set the ARP for a changed IP set.

```
def set_routes(ip_type, ips, interface, mac=None):
    """
    Set the routes on the interface to be the specified set.

    :param ip_type: Type of IP (IPV4 or IPV6)
    :param set ips: IPs to set up (any not in the set are removed)
    :param str interface: Interface name
    :param str mac|NoneType: MAC address. May not be none unless ips is empty.
    """
    if mac is None and ips:
        raise ValueError("mac must be supplied if ips is not empty")

    current_ips = list_interface_ips(ip_type, interface)
    for ip in (current_ips - ips):
        del_route(ip_type, ip, interface)
    for ip in (ips - current_ips):
        add_route(ip_type, ip, interface, mac)
    if ip_type == futils.IPV4:
        for ip in (ips & current_ips):
            futils.check_call(['arp', '-s', ip, mac, '-i', interface])
```

I added the final 3 lines and ARP rules are now being updated correctly.  This was a quick change just to test hypothesis that only changed IPs actually get applied - and probably is not the fix you'd actually want?

**Comment by Lukasa** [comment]
Looks like it's not far from the right fix though. This is for @plwhite.

**Comment by plwhite** [comment]
I have a fix here, not yet tested - so nobody else pick this up when I am out!

**Comment by matthewdupre** [comment]
Fix now merged (PR #600).

**Comment by ed-harrison** [comment]
Reopening as we had to back out the fix in PR #600, which didn't work for IPv6.

**Comment by plwhite** [comment]
Naturally, the area that I broke was a trivial "safe" change to an area with no tests.

I'm going to back off and spend a few happy hours writing endpoint tests to unblock this.

**Comment by fasaxc** [comment]
@plwhite did this get merged for good or did it get backed out again?

**Comment by matthewdupre** [comment]
It's gone in and out several times, but it seems to have stuck this time.
