### ISSUE TITLE
periodic resync thread should yield

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#573]
Occurred to me that the periodic resync thread in the plugin might run for several seconds, which might cause timeouts to API calls.  We should yield every few iterations around our loops.

**Comment by Lukasa** [comment]
The periodic resync thread will not run for several seconds without yielding.

Remember that eventlet yields control at IO events, just like Twisted does, and this entire thing is IO. I think we're *probably* ok on this: I don't believe it's worth doing unless we have a concrete example of this causing problems.

**Comment by fasaxc** [comment]
Make sense, I was casting around for ideas as to how the elector might get starved TBH.
