### ISSUE TITLE
Elections fail on Python 2.6

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#580]
This appears to be a python-etcd incompatibility.  The `handle()` function that is supposed to turn error responses into the EtcdKeyNotFound error that we're expecting, contains this line:
```
msg = '{} : {}'.format(message, cause)
```
Which fails on python 2.6, raising `ValueError('zero length field name in format')`.  That gets translated into a generic EtcdException.

Not sure how much we care about 2.6 support but I think it's broken right now.

**Comment by Lukasa** [comment]
We don't care about this until Python 2.6 support comes back on the table.
