### ISSUE TITLE
Gevent logging exception

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico#587]
Here's a weird one: while trialling our code, @nbartos has hit the following interesting traceback:

```python
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/handlers.py", line 857, in emit
  File "/usr/lib64/python2.7/site-packages/gevent/socket.py", line 441, in send
  File "/usr/lib64/python2.7/site-packages/gevent/socket.py", line 298, in _wait
  File "/usr/lib64/python2.7/site-packages/gevent/hub.py", line 341, in wait
  File "/usr/lib64/python2.7/site-packages/gevent/hub.py", line 568, in get
  File "/usr/lib64/python2.7/site-packages/gevent/hub.py", line 330, in switch
  File "/usr/lib64/python2.7/site-packages/gevent/hub.py", line 334, in switch_out
AssertionError: Impossible to call blocking function in the event loop callback
Logged from file actor.py, line 513
```

My current theory is that we cannot log to syslog from a weakref cleanup callback because that will be called on the main greenlet. I need to confirm that, though.

**Comment by Lukasa** [comment]
Yup, confirmed.

The weakref callback can be thought of as effectively being a destructor. This means they play *really badly* with gevent: if we do anything that could cause gevent to yield the flow of control then we're totally screwed. Because loggers can essentially call arbitrary code, this means we absolutely must not log here.

We should also check our code for any other place we use weakrefs with callbacks, and additionally should confirm that we aren't logging from anything else that is a destructor or destructor-like.

/cc @plwhite @fasaxc

**Comment by Lukasa** [comment]
To be clear, the following comment in the code is wrong in a very subtle way that I did not fully understand until just now:

```python
# Each time we create a TrackedAsyncResult, me make a weak reference to it
# so that we can get a callback (_on_ref_reaped()) when the TrackedAsyncResult
# is GCed.  This is roughly equivalent to adding a __del__ method to the
# TrackedAsyncResult but it doesn't interfere with the GC.
```

It's technically true that the callback does not interfere with GC, but not in the way we had hoped. In particular, the weakref logic is not monkeypatched by gevent, so it's not gevent aware. This means it will run in the context of whatever greenlet is active when the GC fires. 99% of the time we get away with this because we don't do much funky stuff, but that remaining 1% of the time will totally explode, either because we do something funky or because we happen to have interrupted the 'hub' greenlet (which is forbidden from making blocking calls).

The correct solution is to remove the logging from this callback.

**Comment by robbrockbank** [comment]
Do we lose any important information just removing the logs?  Is it worth adding our own log mechanism to queue the logs and write them out on non-hub greenlet?

**Comment by Lukasa** [comment]
I don't believe we do. One of the logs is a debug level log that we clearly don't rely on, and the other is accompanied by a print to stderr (which works fine) and an abrupt exit. Rolling a solution to this problem just to keep those two logs in seems like an error to me.
