### ISSUE TITLE
Neutron driver leader election etcd keys not versioned in data model

### ISSUE THREAD

**Issue by matthewdupre** [Metaswitch/calico#596]
We use version numbers underneath the root `calico` key to ease upgrading the data model, but the leader election keys aren't under it.  Is this intentional?  If so why, if not can we fix it?

Sample etcd contents:
`root@computetest1:~# etcdctl ls --recursive
/calico
/calico/openstack
/calico/openstack/neutron_election
/calico/v1
/calico/v1/policy
/calico/v1/policy/profile
/calico/v1/policy/profile/a0a88dc5-023d-4ce2-af95-6e442c7adfa1
/calico/v1/policy/profile/a0a88dc5-023d-4ce2-af95-6e442c7adfa1/tags
/calico/v1/policy/profile/a0a88dc5-023d-4ce2-af95-6e442c7adfa1/rules
/calico/v1/host
/calico/v1/host/computetest1
/calico/v1/host/computetest1/workload
/calico/v1/host/computetest1/workload/openstack
/calico/v1/host/computetest1/workload/openstack/4e649b23-27a6-4eb8-8f70-85ff917ba28c
/calico/v1/host/computetest1/workload/openstack/4e649b23-27a6-4eb8-8f70-85ff917ba28c/endpoint
/calico/v1/host/computetest1/workload/openstack/4e649b23-27a6-4eb8-8f70-85ff917ba28c/endpoint/7d4454da-0ab6-42b5-890f-9ec1bce4ea58
/calico/v1/config
/calico/v1/config/InterfacePrefix
/calico/v1/Ready`

**Comment by matthewdupre** [comment]
@neiljerram @spikecurtis @lukasa one of you might be able to shed some light on this?

**Comment by neiljerram** [comment]
I think the answer is that during an upgrade, we could have plugins at different levels.  But we still only want one of them to be the leader.

**Comment by lxpollitt** [comment]
@neiljerram I'm not sure I understand your statement.  I agree with it, but don't see why that justifies not having a version number on that part of the data model.  My view is that is should have a version number, but that version number is separate from the version number for the main data model (the data model that Felix interacts with that is not orchestrator specific).  So I would expect /calico/openstack/v1/...

**Comment by neiljerram** [comment]
Suppose one plugin was using /calico/openstack/v1/neutron_election as its leader election key, and another plugin was using /calico/openstack/v2/neutron_election.  How would they avoid deciding both to be the leader, and so both to do periodic resyncs?

**Comment by lxpollitt** [comment]
I'm not sure we have to design that now.  It's a problem to be solved later if/when we do decide we want to make a non-backcompatible change to the data model.  If we put a version number in now then the worst case scenario is we never rev it.

**Comment by ed-harrison** [comment]
@neiljerram @Lukasa @spikecurtis @lxpollitt So what are we doing here (not least, given we've released the code in its current state)?

**Comment by neiljerram** [comment]
Sorry, I've been meaning to follow up...

My feeling is that it would be a bit confusing for some etcd keys to include a version number that looked like it might be the same as the main data model version number, but actually was something different.  So for that reason I'm inclined to prefer leaving it out, as the code stands at the moment.

Also I guess that it would be sufficiently hard to solve the problem sketched above - the transition between two versioned election keys - that it would be no harder to solve it so as to allow an unversioned key as well.  It sounds like possible overengineering to me, to imagine that we'll ever need to address this problem; and even more so to take some guessed step now that might or might not help, and that also costs some immediate confusion.

**Comment by neiljerram** [comment]
As @matthewdupre asked the question originally, maybe he might also want to comment?

**Comment by matthewdupre** [comment]
I haven't had the time to think through the upgrade process in enough detail to come to an opinion here, but here are my current thoughts:

- I'm not convinced we need to version the leader election keys independently (is it really such a bad thing if there's a separate leader for v1 and v2, each owning the appropriate parts of the data model?  I don't have the right background knowledge, but this seems nicer to me.)
- If we do need these keys to be versioned independently, I'm with Neil in that I think it's better if we don't suggest that they share a version.

**Comment by lxpollitt** [comment]
The OpenStack part of etcd is plug-in specific.  There will be other plug-ins.  We won't be the only people writing them.  Therefore each plug-in having its own space in the data model, versioned independently, seems like the right thing to me.  Hence me suggesting /calico/openstack/v1/  (rather than /calico/v1/openstack).

Versioning a data structure that is used to communicate between distributed components is generally good practice.  I am assuming that it is a simple change to insert this versioning.  (Small code change plus a paragraph in the next release note flagging upgrade implications for the release.)  I don't think that's over engineering.  Spending weeks discussing it might be though... ;-)

**Comment by matthewdupre** [comment]
@lukasa @spikecurtis do you agree?

**Comment by Lukasa** [comment]
I think I honestly don't care.
