### ISSUE TITLE
felix can't handle 'other' protocols

### ISSUE THREAD

**Issue by DaveLangridge** [Metaswitch/calico#608]
openstack allows SG rules for 'other' protocols. I tried adding a rule for protocol 132 (SCTP). Openstack was happy with this, but I got no entry in the iptables. felix log:

2015-06-02 15:46:31,338 [ERROR][30619/3] calico.felix.fetcd 514: Validation failed for profile d2571330-c55c-4eb9-a809-654e6cf40603 rules: {'outbound_rules': [{'ip_version': 6, 'dst_net': '::/0'}, {'ip_version': 4, 'dst_net': '0.0.0.0/0'}], 'inbound_rules': [{'ip_version': 4, 'src_tag': u'211588cf-d658-49ca-926a-a14669642645', 'protocol': u'132'}, {'ip_version': 4, 'src_tag': u'd2571330-c55c-4eb9-a809-654e6cf40603', 'protocol': u'icmp'}, {'ip_version': 4, 'protocol': u'tcp', 'src_net': '0.0.0.0/0', 'dst_ports': [22]}]}
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/calico/felix/fetcd.py", line 511, in parse_rules
    common.validate_rules(profile_id, rules)
  File "/usr/lib/python2.7/dist-packages/calico/common.py", line 486, in validate_rules
    raise ValidationFailed(" ".join(issues))
ValidationFailed: Invalid protocol in rule {'ip_version': 4, 'src_tag': u'211588cf-d658-49ca-926a-a14669642645', 'protocol': u'132'}.

**Comment by plwhite** [comment]
We only support tcp, udp, icmp and icmpv6. Either the plugin should be removing these as unsupported or (less short-sightedly) Felix should be handling them. So I think this is a valid bug, and we should fix it, along with ensuring we support anything else that OpenStack can set up (in case we missed anything else).

**Comment by DaveLangridge** [comment]
Openstack supports other protocols, so does iptables. So we should fix this in felix. I'm just testing the other rules.

**Comment by fasaxc** [comment]
@plwhite We need to be careful how we firewall this; we don't want to allow combinations that iptables doesn't support.  For example, iptables only allows the "multiport" match extension (which we use for matching ports) with tcp, udp, udplite, dccp and sctp.

Also 0 and all are (synonymous) special values.

**Comment by DaveLangridge** [comment]
I think 0 is a valid protocol. 'all' is a special value (enter '-1' on horizon).
I think I also suggested that this rule was rejected, but others in the SG were applied. I don't think that's always true. e.g. if this rule is first? Makes fixing more urgent.

**Comment by DaveLangridge** [comment]
Also, horizon doesn't give the option of specifying ports when 'other protocol' is selected.

**Comment by ed-harrison** [comment]
If there are things one can configure for SG's in OpenStack, which can't be represented by iptables, then we need to be quite careful about how we present this.  From a 1000 foot view, I'd expect that the OpenStack user will need to know that their rules have been rejected (i.e. there is some kind of error in Horizon or on the CLI) - we'll also need to clearly document the restrictions somewhere.

**Comment by DaveLangridge** [comment]
Sorry if I wasn't clear above. You can't specify port in the 'other protocols' rule, so the inability of iptables to match port for other protocols isn't relevant to us.

**Comment by fasaxc** [comment]
@DaveLangridge sorry, I mean iptables treats 0 as a special value, which means all; I think matching on protocol == 0 is possible but requires a special case.  iptables is a bit of a minefield.

@ed-harrison agreed; IIRC @neiljerram said that wasn't easy to plumb through but maybe we should revisit.  There's another case that I know we can't handle: #424  .  If we could give a clean error then I'd argue we should do that rather than bending over backwards to support a match that is pretty meaningless anyway.

**Comment by fasaxc** [comment]
I'll grab this one since I'm probably the most familiar with the iptables stuff at this point.
