### ISSUE TITLE
Protect against full conntrack table

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#617]
As per #616 customer was doing heavy churn and managed to fill up the conntrack table.  #616 covers improving the install process to cover setting the conntrack limit appropriately.  This issue covers investigating whether there are other areas we can tune or rules we can install to avoid getting DoSed by a full table.

Presently, when the table fills up, you can't even ssh into the host to investigate and it's possible for a VM to deliberately try to fill up the table by creating lots of connections.

We may just want to document best practice or there may be impacts for our iptables programming to, for example, prioritise traffic to the host over traffic to the guests.

**Comment by Lukasa** [comment]
We've done some documentation and #623, so I'm calling this done for now.
