### ISSUE TITLE
Remove conntrack entries for deleted endpoint?

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#618]
As per #616, customer was doing heavy churn, filling up the conntrack table.  One particular issue was that, each time they deleted a VM, they had to wait for the conntrack entries for that VM to time out.  the default timeout is very long so the table filled up.

Can we do something better than recommending a lower timeout.  For example, having felix remove the entries when an endpoint disappears?

**Comment by fasaxc** [comment]
Had a quick look at the conntrack tools.  It looks like we could have felix issue a pair of calls for each removed IP address:
```
conntrack --delete --orig-src <ip>
conntrack --delete --orig-src <ip>
```
Those delete all the conntrack entries that are going to/from the relevant IP.

**Comment by fasaxc** [comment]
@Lukasa, IIRC you tried something like that but it didn't fly for some reason; can you remember what that was?

**Comment by Lukasa** [comment]
I have no recollection of having tried anything like this, so I'm not sure how to help. You sure it was me?

**Comment by ed-harrison** [comment]
@fasaxc is addressing under #623

**Comment by fasaxc** [comment]
With me to have a think if there's any race conditions with a new endpoint being added on the same host with reused IP.
