### ISSUE TITLE
Felix can write to two logfiles.

### ISSUE THREAD

**Issue by DaveLangridge** [Metaswitch/calico#624]
Confusing. One has logs reading config from etcd correctly, the other has 'EtcdException: Unable to decode server response: timed out' (I'll raise another issue for that.)

[root@calico-rh01 calico]# ls -ltr
total 27784
-rw-r--r--. 1 root root   496320 Jun  5 10:24 felix.log.2015-06-03
-rw-r--r--. 1 root root 19568895 Jun  5 10:24 felix.log

**Comment by DaveLangridge** [comment]
I've just noticed that the felix exception appears in both log files.

**Comment by fasaxc** [comment]
Conflict between log-rotate and felix?

**Comment by fasaxc** [comment]
@plwhite I think you wrote the logging setup, are you a good person to look at this?

**Comment by matthewdupre** [comment]
I think in general we need to sort out our log rotation story.  There's also a problem on Ubuntu, where Felix does its own log rotation, but so does upstart, leading to ridiculously named log files.

**Comment by matthewdupre** [comment]
@DaveLangridge could you please confirm that there was only one Felix running?

**Comment by DaveLangridge** [comment]
Yes. Only one felix.

**Comment by Lukasa** [comment]
Closing this as a duplicate of #249, we'll centralise work there.
