### ISSUE TITLE
Rule with 0 in port range is rejected by kernel, prevents profile update

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#631]
The multiport iptables extension doesn't like 0 as a tcp port but OpenStack allows 0 to be configured.  We should firewall against this in Felix:

* If 0 really is a valid port for the given profile, we should figure out how to match on it.
* It it is not a valid port, then we should probably just program range 0-n as 1-n instead.

The impact of trying to program a bad rule like this is that the iptables update fails.  We catch that error for profile and endpoint chain updates in order to limit the impact to the single profile or endpoint.

**Comment by matthewdupre** [comment]
We should find out what vanilla OpenStack does with this rule.

**Comment by fasaxc** [comment]
@matthewdupre given how limited Openstack rules are, I bet they use `-m tcp -sport a:b`, which is what my fix does to handle 0.  We were using `-m multiport -sports a:b,c,d`, which allows for lists of ports but it doesn't allow 0.  There'd be no reason for them to use that since they didn't support lists.

**Comment by fasaxc** [comment]
Fixed in #649.  Turned out to be over-active validation rather than kernel limitation.
