### ISSUE TITLE
New felix-INPUT chain prevents exposing service from host

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#659]
Piston Cloud expose more than just the metadata service from the host to VM.  Our tightening up of the rules under #636 has broken that because the packets from VMs hit our "DENY from tap+" rule before getting to Piston's own rules.

In general, I think we need some supported way to do this.  Ideally, a way that encompasses the special-case of the metadata service in a generic way.  We also need a pragmatic solution for @nbartos for hte short term.

**Comment by nbartos** [comment]
It should be noted that in the final solution, the VM's security policy should be respected for all the other services we are allowing.  For example if the VM's security policy states to drop all outbound, then the VM shouldn't be able to connect to the services we are running on the hypervisor.

**Comment by Lukasa** [comment]
Agreed.

I think the correct approach is to add an extra bit of configuration, stored in etcd, that essentially provides for something like a global security profile that applies to the INPUT chain.

**Comment by nbartos** [comment]
It seems like it could be done more elegantly than that somehow (also keep in mind our current utilization of etcd and how it gets wiped often).  At the moment I'm not seeing a disadvantage to always taking into account the security policy on the INPUT chain.

**Comment by Lukasa** [comment]
Well, the biggest issue is preventing tenants from configuring 'allow all OUTBOUND' and then port scanning their host looking for vulnerable services. We do need some form of denial of access for tenants and the fabric.

I agree that we can take into account the tenants security policy, that's a no brainer. What I was talking about in this case is how we allow you to offer access to your services on the host while protecting the rest of the host from the guests.

**Comment by nbartos** [comment]
I believe if this is done correctly, the other rules (and/or the default policy) set up before felix starts (that end up after the felix jumps) will take care of that.  I don't think Calico should override what the default policy is on the host.  Anyone concerned about security (and _everyone_ should be) should have set their default policy on INPUT and FORWARD in the filter table to DROP.

**Comment by fasaxc** [comment]
@Lukasa I'm wondering if we should back out the input chain change for now and plug the 127.0.0.1 hole directly.  Then we can spend some time designing this piece (it overlaps with a lot of other areas too, such as bare-metal support and network-wide ACLs).

@nbartos just to make sure I'm following, are you suggesting that felix should let packets fall off the bottom of its chain (to be processed by default policy) rather than dropping them?

**Comment by fasaxc** [comment]
Also wondering how we solve the problem of not clobbering pre-existing rules.  Felix will always insert its rules at the top of the chain, which may be incorrect.  One way that springs to mind is to make it configurable which chain felix inserts its top-level rule into.  Then the operator can have ownership of the INPUT chain and jump to us when they're ready.

**Comment by nbartos** [comment]
Yes I was suggesting it should fall off the bottom of the chain (or explicitly return, depending on what is done).  I believe this is what was happening before.  It probably deserves more thought too, about how these sort of things should mesh into the VMs security policy rules.  The VM security policy should always be respected.  For example if the VM doesn't have a matching allow rule on the outbound side (e.g. the default allow everything rule or a special one), it shouldn't have access to the service running locally on the hypervisor (consistent with having the same service running on another machine).

**Comment by fasaxc** [comment]
@nbartos I've put up a PR (#661) that should resolve this.  It reinstates the policy on the input chain and makes the end-of-chain action configurable for the felix-INPUT chain.  It defaults to DENY but can be set to RETURN or ACCEPT using the config file.  The new parameter is "DefaultEndpointToHostAction".

I've given it a spin locally and I'm seeing the rules I expect but I'd appreciate if you could test that it solves the issue in context.  Thanks.
