### ISSUE TITLE
VM stuck with status shutoff following power cycle of compute host

### ISSUE THREAD

**Issue by MatMeredith** [Metaswitch/calico#666]
Following power cycle of compute host, I've seen VMs getting stuck in state shutoff/shutdown.   Any attempt to restart the VM fails with the following logs in libvirtd.log on the compute host.

Jun 19 11:10:17 calico-cidev14 kernel: [ 1298.116871] type=1400 audit(1434708617.071:75): apparmor="DENIED" operation="open" profile="/usr/lib/libvirt/virt-aa-helper" name="/etc/nsswitch.conf" pid=3173 comm="virt-aa-helper" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Jun 19 11:10:17 calico-cidev14 kernel: [ 1298.117007] type=1400 audit(1434708617.071:76): apparmor="DENIED" operation="open" profile="/usr/lib/libvirt/virt-aa-helper" name="/etc/nsswitch.conf" pid=3173 comm="virt-aa-helper" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Jun 19 11:10:17 calico-cidev14 kernel: [ 1298.117119] type=1400 audit(1434708617.071:77): apparmor="DENIED" operation="open" profile="/usr/lib/libvirt/virt-aa-helper" name="/etc/passwd" pid=3173 comm="virt-aa-helper" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Jun 19 11:10:17 calico-cidev14 kernel: [ 1298.117135] type=1400 audit(1434708617.071:78): apparmor="DENIED" operation="open" profile="/usr/lib/libvirt/virt-aa-helper" name="/etc/passwd" pid=3173 comm="virt-aa-helper" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

Diags from the compute host @ https://transfer.sh/XjjfX/compute-host-diags.tar.xz

**Comment by fasaxc** [comment]
@MatMeredith Any reason to suspect this isn't an upstream bug?

**Comment by MatMeredith** [comment]
No – that seems most likely.

**Comment by Lukasa** [comment]
Ok, in that case let's close this down until we have any reason to believe otherwise.
