### ISSUE TITLE
Make INPUT chain generic and configurable.

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico#668]
The code that handles the INPUT chain is really complicated, and probably needs to be refactored to be cleaner. It may also want some tests.

We also need to consider whether we need a more formal approach for handling the INPUT chains.

See #661, #659, #660, #636, #658, #665, and #667 for examples of the problems we've encountered here.

**Comment by fasaxc** [comment]
I'd like to make this all generic and configurable (we shouldn't have special cases for OpenStack metadata, DNS, DHCP, etc).  However, there are lots of requirements to consider and lots of future enhancements that this overlaps with:

* Need the metadata IP to be settable from the config file.
* Need NAT and filter policy.
* In future, we'd like to have global policy (to allow the network security team to put an upper bound on the policy that developers can configure for their hosts) and per-host bare-metal policy (to secure the host itself).
* It should be agnostic to where the traffic came from.  The policy should apply equally to local VMs and to VMs on other hosts, for example.

**Comment by fasaxc** [comment]
I think #681 improves this a bit.

**Comment by Lukasa** [comment]
I think for now we can close this. We just need to stay aware of it as we add features in future.
