### ISSUE TITLE
Documentation is fuzzy on security configuration

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#669]
Calico currently provides application-level firewalling: the developer of an app/admin of a workload configures the ports that they want to open etc.  However, that's only one piece of the puzzle.  We need to be clear about how Calico fits into an overall security architecture and where our responsibilities end.

For example, to secure OpenStack, running Calico isn't enough right now; you very likely want to:
* set the default iptables policy to DROP for the INPUT and FORWARD chains so that unexpected traffic to the host is dropped by default
* apply your own iptables rules to whitelist services running on the hosts
* configure selinux etc.
* firewall etcd.
* configure conntrack for appropriate levels of scale and timeouts to prevent DoS

**Comment by matthewdupre** [comment]
Note that 'configure selinux' clashes with the RHEL install instruction to disable selinux on the compute hosts (it's disabled by default on Ubuntu, so we may well have the same issue there).  As far as I'm aware, we haven't done a detailed investigation into what the cost of this is, and whether there's a more fine grained option.
