### ISSUE TITLE
Rebuilt VMs can't DHCP

### ISSUE THREAD

**Issue by lwr20** [Metaswitch/calico#67]
Scenario: I'm using an Openstack system with Calico installed.  It has 3 compute nodes and a controller.  I create a VM - it comes up as expected and I can ssh into it.  In Horizon, I click "rebuild".  The VM gets rebuilt as expected, but it fails to DHCP its IP address and ends up with no network connectivity.

Readily reproducible.

/var/syslog on the compute host housing the VM shows that dnsmasq is seeing the DHCPDISCOVER and is responding with a DHCPOFFER.  But the VM does not appear to see it:

Dec 15 17:46:46 linux-esx3-067 kernel: [26762.648182] type=1400 audit(1418665606.171:227): apparmor="DENIED" operation="exec" profile="libvirt-1d531018-e364-471c-845b-c60155533b64" name="/etc/qemu-ifdown" pid=12817 comm="qemu-system-x86" requested_mask="x" denied_mask="x" fsuid=108 ouid=0
Dec 15 17:46:46 linux-esx3-067 kernel: [26763.143547] type=1400 audit(1418665606.667:228): apparmor="STATUS" operation="profile_remove" profile="unconfined" name="libvirt-1d531018-e364-471c-845b-c60155533b64" pid=12819 comm="apparmor_parser"
Dec 15 17:46:47 linux-esx3-067 kernel: [26763.766128] IPv6: ADDRCONF(NETDEV_UP): tap47d10009-ba: link is not ready
Dec 15 17:46:47 linux-esx3-067 kernel: [26764.073209] type=1400 audit(1418665607.595:229): apparmor="STATUS" operation="profile_load" profile="unconfined" name="libvirt-1d531018-e364-471c-845b-c60155533b64" pid=12881 comm="apparmor_parser"
Dec 15 17:46:47 linux-esx3-067 kernel: [26764.099076] IPv6: ADDRCONF(NETDEV_CHANGE): tap47d10009-ba: link becomes ready
Dec 15 17:46:49 linux-esx3-067 ntpd[2118]: Deleting interface #50 tap47d10009-ba, fe80::50af:93ff:fe2e:ac0a#123, interface stats: received=0, sent=0, dropped=0, active_time=1936 secs
Dec 15 17:46:49 linux-esx3-067 ntpd[2118]: peers refreshed
Dec 15 17:46:51 linux-esx3-067 ntpd[2118]: Listen normally on 51 tap47d10009-ba fe80::a409:cff:fe5d:5487 UDP 123
Dec 15 17:46:51 linux-esx3-067 ntpd[2118]: peers refreshed
Dec 15 17:46:51 linux-esx3-067 ntpd[2118]: new interface(s) found: waking up resolver
Dec 15 17:46:55 linux-esx3-067 dnsmasq-dhcp[17542]: DHCPDISCOVER(ns-68eec767-8e) fa:16:3e:a1:7e:b9
Dec 15 17:46:55 linux-esx3-067 dnsmasq-dhcp[17542]: DHCPOFFER(ns-68eec767-8e) 10.65.0.75 fa:16:3e:a1:7e:b9
Dec 15 17:47:55 linux-esx3-067 dnsmasq-dhcp[17542]: DHCPDISCOVER(ns-68eec767-8e) fa:16:3e:a1:7e:b9
Dec 15 17:47:55 linux-esx3-067 dnsmasq-dhcp[17542]: DHCPOFFER(ns-68eec767-8e) 10.65.0.75 fa:16:3e:a1:7e:b9
Dec 15 17:48:55 linux-esx3-067 dnsmasq-dhcp[17542]: DHCPDISCOVER(ns-68eec767-8e) fa:16:3e:a1:7e:b9
Dec 15 17:48:55 linux-esx3-067 dnsmasq-dhcp[17542]: DHCPOFFER(ns-68eec767-8e) 10.65.0.75 fa:16:3e:a1:7e:b9
Dec 15 18:00:01 linux-esx3-067 CRON[13014]: (neutron) CMD (if [ -x /usr/bin/neutron-netns-cleanup ] ; then /usr/bin/neutron-netns-cleanup --config-file=/etc/neutron/neutron.conf --config-file=/etc/neutron/l3_agent.ini >/dev/null 2>&1; fi)

**Comment by Lukasa** [comment]
Ok, so here's what happens: when you hit 'rebuild VM', one of the things nova does is delete the tap interface and recreate it, without telling neutron anything about it. This means that Felix doesn't know the interface went away and then came back.

Unfortunately, when the interface was removed the route to the VM was also removed by the kernel, which means the VM becomes unrouteable until Felix resyncs. This can be seen by hitting 'rebuild VM' and then restarting Felix on the compute host. The guest will then successfully DHCP.

**Comment by Lukasa** [comment]
Fixing this will likely be tricky.

**Comment by Lukasa** [comment]
*Probably* the correct logic is this:

Felix should watch netlink to spot when devices leave and are created. If at any point a tap interface is created that matches one Felix already knows about, it should re-program it appropriately.

**Comment by Lukasa** [comment]
@plwhite, thoughts on that?

**Comment by Lukasa** [comment]
I believe that fixing this will be a substantial chunk of work, and will be a lot easier following the Felix threading refactor, so I propose we hold off on this for now.

**Comment by Lukasa** [comment]
For when we come back to this, [here's a quick example](https://gist.github.com/Lukasa/6209575d588f1584c374) of how to listen for link up events in Python.

**Comment by fasaxc** [comment]
We now listen on the netlink API.  @lwr20 can you repro this now?

**Comment by lwr20** [comment]
This bug no longer repros.
