### ISSUE TITLE
Unhelpful log from Felix when cluster ID changes

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico#676]
I've labelled this as a Felix bug but it's actually a python-etcd bug, I just want to make sure we track it here.

When the etcd cluster ID changes Felix emits a log that looks like this:

```
2015-06-22 14:49:12,465 [WARNING][20651/3] calico.felix.fetcd 350: Out of sync with etcd (EtcdClusterIdChanged('The UUID of the cluster changed from None to None.',)).  Reconnecting for full sync.
```

Note that the UUID is identical. This will *always* be the case, because python-etcd overwrites the expected cluster ID before logging it out. Simple logging bug there, should be easily fixed.

**Comment by Lukasa** [comment]
(For those who care, the context here is that the etcd proxy fell over and lost its connection to the etcd cluster, causing the cluster ID to become `None`. That may be another bug, by the way: I don't think the cluster ID change is the main problem here.)

**Comment by alexwlchan** [comment]
I had two minutes to spare, so I submitted a fix to python-etcd: https://github.com/jplana/python-etcd/pull/113

**Comment by Lukasa** [comment]
Hmm: that's upstream. @fasaxc, are we still maintaining any patches against upstream?

**Comment by Lukasa** [comment]
Also, thanks @alexwlchan!

**Comment by fasaxc** [comment]
@Lukasa yeh, I think we've got a couple of patches in our tree at the moment.  Upstream was moving pretty fast and they accepted my patch to improve exception handling (which will require felix changes) a little while ago.

**Comment by Lukasa** [comment]
Ok, cool. So @alexwlchan, we need that patch against the Metaswitch fork as well please!

**Comment by alexwlchan** [comment]
@Lukasa Here you go: https://github.com/Metaswitch/python-etcd/pull/8

**Comment by Lukasa** [comment]
Thanks! \o/
