### ISSUE TITLE
Missing docs link to common install steps

### ISSUE THREAD

**Issue by plwhite** [Metaswitch/calico#683]
From the ubuntu install instructions, and the RedHat ones.

    Common Steps
    Some steps need to be taken on all machines being installed with Calico. These steps are detailed here.

That's nice - but there is no link here, and no obvious place to go from here.

**Comment by Lukasa** [comment]
Are you sure this is a problem? If you check the rendered page you'll notice that the paragraph in question is the first paragraph in a section (entitled Common Steps), that then describes what those steps are. The most substantial change I'd want to make here is maybe to change 'detailed here' to 'detailed in this section'. Is that sufficiently substantial for you @plwhite?

**Comment by matthewdupre** [comment]
I can confirm that there is no intention to link to a separate document from there.

**Comment by plwhite** [comment]
@Lukasa  Yes, that would do it, thanks. It never occurred to me that is what it meant so I think that trivial clarification is needed.

I don't have time to fix before going on holiday so I'm not going to sit on this issue.
