### ISSUE TITLE
One gateway for multiple IPv6 addresses

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico#717]
Per the data model, an endpoint has the following possible data in it:

```
{"ipv6_gateway": <some_ip>, "ipv6_nets": [<list of subnets>]}
```

The problem is, that doesn't work. OpenStack will quite happily let you assign multiple addresses to an endpoint that are in subnets with different gateways, and it doesn't appear that there's anything wrong with that. Of course, if you do that the VM will break because we won't set up proxy NDP properly, and everything will go wrong.

I think gateways need to be scoped to specific subnets.

People who need to be aware of this: @fasaxc @neiljerram @spikecurtis @plwhite

**Comment by spikecurtis** [comment]
@Lukasa Can you be more specific about "the VM will break"?

Also, your view of the data model isn't quite right.  The `ipv6_nets` is not a "list of subnets" that the endpoint _belongs to_, it's a list of _network prefixes_ describing the addresses of the endpoint.  I.e. Felix should insert a route into the host routing table for every one of those nets pointing to the tap/veth for that endpoint.

In contrast, a _subnet_ tells the guest OS about what IP addresses are on link.  Some OSes may have difficulty dealing with multiple subnet prefixes on a single interface, I don't know.  But, if operating correctly, you only need one default gateway, no matter how many subnet prefixes.  The gateway just needs to be on-link.  **However, the configuration of subnets on the guest has to do with DHCPv6 or ICMPv6 Router Advertisements, not proxy NDP.**

Taking a step back, what are you trying to accomplish that isn't working?

**Comment by Lukasa** [comment]
> Can you be more specific about "the VM will break"?

You can see the relevant code pretty easily. [This](https://github.com/Metaswitch/calico/blob/cbb92d2be88dc026ba6efcb4a238d949a02c1eea/calico/felix/endpoint.py#L383-L384) is the only place in the code that touches the `ipv6_gateway` field in the data model, which will then use it for [this](https://github.com/Metaswitch/calico/blob/cbb92d2be88dc026ba6efcb4a238d949a02c1eea/calico/felix/devices.py#L133-L135). I am assuming all that work is required. I admittedly haven't tried, but my assumption is that the guest will attempt to contact its gateway (as learned from DHCPv6) and we may not proxy the NDP, because we've associated it with another gateway.

Is that wrong?

**Comment by spikecurtis** [comment]
@Lukasa I added that code specifically for `calico-docker`, which doesn't use DHCP at all.  It simply tells the host to proxy the gateway IP address over NDP on that link.  So, if the guest needs to re-resolve the gateway's MAC address, it can.

This wasn't required in the OpenStack case because the DHCP server periodically transmits Router Advertisements to the guest, allowing the guest to keep its neighbor cache entry for the gateway hot without using NDP.

I still don't get what you're trying to accomplish that doesn't work, or what you're concerned won't work in the future.  What's the big picture here?

**Comment by Lukasa** [comment]
@spikecurtis The specific concern is just that we may want to allocate multiple addresses to endpoints, and that those addresses may logically have different gateway IP addresses. This is allowable in OpenStack, and so is something we need to support there. If we don't need the Proxy NDP side of things, and you don't think this is a use-case we need to support in calico-docker, then we can leave it alone and call this not-a-bug. =)

**Comment by Lukasa** [comment]
Ok, I'm convinced the bug in this form doesn't exist. =)
