### ISSUE TITLE
Felix: Cannot disable file or stdout/stderr logging

### ISSUE THREAD

**Issue by nbartos** [Metaswitch/calico#72]
In felix.conf, commenting out "LogFilePath" results in the startup error:
OSError: [Errno 2] No such file or directory: ''

Additionally, there does not seem to be a way to disable logging to stdout/stderr.

On systems where the only desired logger is syslog, it would be nice to not have to set these manually to /dev/null.

This may also be a problem with the other daemons.

**Comment by lwr20** [comment]
Fix for this was merged into master in pull request #81.

**Comment by plwhite** [comment]
This fix was bad - reopening.

**Comment by lwr20** [comment]
New fix looks much better.  Closing.
