### ISSUE TITLE
Communication with host filtered, even if the profile is allow all.

### ISSUE THREAD

**Issue by spikecurtis** [Metaswitch/calico#723]
Seen on v0.26

Set up two endpoints (containers), both part of a single profile with allow all in both inbound and outbound rules.  Host can successfully ping each container, containers can successfully ping each other, but containers cannot ping the host.

iptables-save here: https://gist.github.com/spikecurtis/e3131fd5650ff7097232

**Comment by Lukasa** [comment]
IMO this is working as designed, with the change being introduced in #636 (and refined a few times afterward).

Generally speaking the endpoint is not the only machine that should control where its packets go, and generally hosts will want to remove as much of their connection surface as possible when contacted by VMs. We are probably missing some function to allow certain host ports and traffic behaviour, but for now per #660 you can change the DROP to a RETURN if you don't want the filtering behaviour.

We *may* want to enhance the logic to allow ICMP packets through, however.

**Comment by fasaxc** [comment]
Yep, as Cory said, there's a config option to control what happens to unmatched host-bound packets and we set it to DROP by default.  Not obvious what the default should be but DROP feels safer so we went with that.

FTR, the config option is DefaultEndpointToHostAction and you can set it to "RETURN" "DROP" or "ACCEPT".  Looks like I forgot to add that to the docs.  With me:

[ ] Add to DefaultEndpointToHostAction to the docs

**Comment by spikecurtis** [comment]
@Lukasa Allowing the endpoint to ping but not UDP or TCP to the host is just going to be more confusing than just blocking everything.

**Comment by kriss9** [comment]
For now, this did the trick -- 
# for x in `etcdctl ls /calico/v1/host/ | cut -d/ -f5`; do etcdctl set /calico/v1/host/$x/config/DefaultEndpointToHostAction RETURN; done
