### ISSUE TITLE
iptables-restore fails.  "Set felix-calico-hosts-4 doesn't exist."

### ISSUE THREAD

**Issue by spikecurtis** [Metaswitch/calico#724]
Setup is a single host with two containers, and one profile with allow all in and out.  Running on Felix 0.26.

Gist here: https://gist.github.com/spikecurtis/c33af8fa088e495185f8

Full diags:
https://transfer.sh/yXXAf/diags-140715-093309.tar.gz

**Comment by fasaxc** [comment]
Dupe of #707?

**Comment by fasaxc** [comment]
Please retest with 0.27, which contains the fix for #707.

**Comment by spikecurtis** [comment]
Works on 0.27.  Closing.
