### ISSUE TITLE
Daemons should allow binding to a specific address

### ISSUE THREAD

**Issue by nbartos** [Metaswitch/calico#73]
Currently daemon bind statements do not allow specifying a specific IP address to bind to.  This is necessary/desirable on some machines with multiple IP addresses that serve a variety of functions.

Example output of netstat:
tcp        0      0 0.0.0.0:9902            0.0.0.0:*               LISTEN      32153/python2.7     
udp        0      0 0.0.0.0:47502           0.0.0.0:*                           32153/python2.7     
tcp        0      0 0.0.0.0:9905            0.0.0.0:*               LISTEN      367/python2.7       
tcp        0      0 0.0.0.0:9906            0.0.0.0:*               LISTEN      367/python2.7  

Relevant code sections:
calico/openstack/mech_calico.py:        self.felix_router_socket.bind("tcp://*:%s" % PLUGIN_ENDPOINT_PORT)
calico/openstack/mech_calico.py:        self.acl_get_socket.bind("tcp://*:%s" % PLUGIN_ACLGET_PORT)
calico/openstack/mech_calico.py:        self.acl_pub_socket.bind("tcp://*:%s" % PLUGIN_ACLPUB_PORT)
calico/felix/fsocket.py:            self._zmq.bind("tcp://*:%s" % self.port)
calico/acl_manager/acl_publisher.py:        self.router_socket.bind("tcp://*:%s" % MANAGER_ACLGET_PORT)
calico/acl_manager/acl_publisher.py:        self.pub_socket.bind("tcp://*:%s" % MANAGER_ACLPUB_PORT)

**Comment by plwhite** [comment]
Resolved by pull request #82

**Comment by Lukasa** [comment]
This was fixed in #82. Thanks for the report @nbartos.
