### ISSUE TITLE
Calico Neutron Agent does not allow setting host parameter

### ISSUE THREAD

**Issue by nbartos** [Metaswitch/calico#77]
Neutron agents (neutron-dhcp-agent, neutron-metadata-agent, etc) have a setting in their config file called "host", which is defined in neutron/common/config.py and defaults to utils.get_hostname().

Setting this parameter works fine for the neutron agents that ship with neutron, however it does not work for the Calico agent.

As our environment does not have hostnames which are resolvable from other nodes, we set the Neutron/Nova/etc hostnames to the IP address so all nodes can access each other.

**Comment by plwhite** [comment]
Neil, I assigned this to you because it seems more likely that you can make progress on it, and it's on our list to fix.

**Comment by Lukasa** [comment]
@plwhite I disagree. Felix reports back its hostname to the plugin in [its resyncstate request](https://github.com/Metaswitch/calico-docs/wiki/Calico-API-Proposal#request-resyncstate). This is the information that needs to be changed, so Felix needs configuration to do it.

**Comment by plwhite** [comment]
Agreed - think I misread it. Taking it back for fixing.

**Comment by Lukasa** [comment]
@nbartos This functionality was merged in #84. Thanks so much for reporting it!
