### ISSUE TITLE
Log parameters not respected for acl manager

### ISSUE THREAD

**Issue by nbartos** [Metaswitch/calico#78]
I tried using the following settings for acl manager like I have set for felix:

LogSeverityFile   = CRITICAL
LogSeveritySys    = INFO
LogSeverityScreen = CRITICAL

However they are not respected.  A quick grep shows these as being only in felix.  It looks like acl manager only supports LogFilePath.

It would be nice if setting up the logging was common code and just imported in felix and acl-manager, so the logging could be consistent and log to syslog correctly.

**Comment by plwhite** [comment]
Lance, I believe you made or are making a fix which resolves this together with bug #72, right? In that case, I think you should own this issue.

**Comment by Lukasa** [comment]
@nbartos This was resolved in #85. Thanks for reporting!
