### ISSUE TITLE
We do not support an IP v6 only compute host

### ISSUE THREAD

**Issue by plwhite** [Metaswitch/calico#83]
We use IP v4 for our `0MQ` communications. We ought to allow IP v6 too, which would require us to allow the specification of IP v6 addresses and also the use of IP v6 with `0MQ` (see the `ZMQ_IPV4ONLY` flag).

This is easy to fix, but a bit of a pain to test, so we won't fix it right away.

**Comment by fasaxc** [comment]
Pre-etcd: closing.
