### ISSUE TITLE
Felix can break external access to port 80 on the host

### ISSUE THREAD

**Issue by plwhite** [Metaswitch/calico#88]
This breaks horizon quite nicely, for example.

Fix available in pull request #87

**Comment by lwr20** [comment]
Just to be clear, this means that attempting to use a single host as Compute and Controller will break Horizon.

**Comment by Lukasa** [comment]
PR #87 does not fix this bug.

**Comment by Lukasa** [comment]
Whoops, yes it does. Ugh, iptables.
